#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154
# Packager: sektor

pkgname=grub
pkgver=2.14_rc1
_srcver=2.14~rc1
pkgrel=1slint
source=(
  "https://alpha.gnu.org/gnu/grub/grub-${_srcver}.tar.xz"
  "0001-00_header-add-GRUB_COLOR_-variables.patch"
  "0003-support-dropins-for-default-configuration.patch"
  "add_initrd_names_and_load_video_module_for_linux.diff"
  "skip.new.orig.diff"
  "grub.conf"
  "post-upgrade-grub"
  "update-grub"
  "GRUB_configuration"
  "unifont-12.1.02.bdf"
)
url="https://www.gnu.org/software/grub/"
options=("nosrcpack" "noautodotnew")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"grub (the GRand Unified Bootloader)"
""
"GNU GRUB is a multiboot boot loader."
""
"It provides BIOS and EFI boot loaders plus grub-install and"
"grub-mkconfig support for generating boot menus."
""
"Slint includes update-grub and post-upgrade integration helpers."
""
""
)

doinst() {
  config() {
    NEW="$1"
    OLD="$(dirname "$NEW")/$(basename "$NEW" .new)"
    if [ ! -r "$OLD" ]; then
      mv "$NEW" "$OLD"
    elif [ "$(md5sum "$OLD")" = "$(md5sum "$NEW")" ]; then
      rm "$NEW"
    fi
  }

  for file in etc/grub.d/*.new; do
    [ -e "$file" ] || continue
    config "$file"
  done
  config etc/default/grub.new
  [ -f /etc/slint-version ] && sh /usr/sbin/post-upgrade-grub
}

build() {
  local build_cflags build_cxxflags font_size platform

  cd "${pkgname}-${_srcver}" || return 1

  # Let grub-mkfont find DejaVuSans.ttf in current Slackware font paths.
  sed -i \
    's|/usr/share/fonts/dejavu|/usr/share/fonts/dejavu /usr/share/fonts/TTF|g' \
    configure.ac || return 1

  patch -p1 --verbose < ../add_initrd_names_and_load_video_module_for_linux.diff || return 1
  sed -i 's|GNU/Linux|Linux|' util/grub.d/10_linux.in || return 1
  patch -p1 --verbose < ../skip.new.orig.diff || return 1
  patch -p1 --verbose < ../0001-00_header-add-GRUB_COLOR_-variables.patch || return 1
  patch -p1 --verbose < ../0003-support-dropins-for-default-configuration.patch || return 1

  autoreconf -vif || return 1

  case "$ARCH" in
    i?86|x86_64)
      build_cflags="-O2 -mtune=generic"
      build_cxxflags="-O2 -mtune=generic"
      ;;
    *)
      build_cflags=${CFLAGS//-fPIC/}
      build_cxxflags=${CXXFLAGS//-fPIC/}
      ;;
  esac

  for platform in i386-pc x86_64-efi x86_64-emu i386-efi; do
    mkdir -p "build_${platform}" || return 1
    cd "build_${platform}" || return 1

    CFLAGS="$build_cflags" \
    CXXFLAGS="$build_cxxflags" \
    ../configure \
      --with-platform="${platform##*-}" \
      --target="${platform%%-*}" \
      --prefix=/usr \
      --libdir="/usr/lib${LIBDIRSUFFIX}" \
      --sysconfdir=/etc \
      --localstatedir=/var \
      --infodir=/usr/info \
      --mandir=/usr/man \
      --enable-cache-stats \
      --enable-boot-time \
      --enable-grub-mount \
      --enable-device-mapper \
      --disable-werror || return 1

    make -j"$numjobs" || make || return 1
    if [ "$platform" = "i386-pc" ]; then
      make html || return 1
    fi
    make install DESTDIR="$PKG" || return 1
    cd .. || return 1
  done

  if [ -e "$PKG/etc/bash_completion.d/grub" ]; then
    mkdir -p "$PKG/usr/share/bash-completion/completions" || return 1
    mv "$PKG/etc/bash_completion.d/grub" \
      "$PKG/usr/share/bash-completion/completions/grub" || return 1
    rmdir --parents "$PKG/etc/bash_completion.d" 2>/dev/null || true
  fi

  for file in "$PKG"/etc/grub.d/*_*; do
    [ -e "$file" ] || continue
    mv "$file" "${file}.new" || return 1
  done

  install -Dm0644 ../grub.conf "$PKG/etc/default/grub.new" || return 1
  install -Dm0755 ../post-upgrade-grub "$PKG/usr/sbin/post-upgrade-grub" || return 1
  install -Dm0755 ../update-grub "$PKG/usr/sbin/update-grub" || return 1
  mkdir -p "$PKG/boot/grub" || return 1

  "$PKG/usr/bin/grub-mkfont" -o "$PKG/usr/share/grub/unicode.pf2" \
    -abv ../unifont-12.1.02.bdf || return 1
  font_size=${FONT_SIZE:-19}
  if [ -r /usr/share/fonts/TTF/DejaVuSansMono.ttf ]; then
    "$PKG/usr/bin/grub-mkfont" \
      -o "$PKG/usr/share/grub/dejavusansmono.pf2" \
      -abv \
      -s "$font_size" \
      /usr/share/fonts/TTF/DejaVuSansMono.ttf || return 1
  fi

  install -d "$PKG/usr/doc/${pkgname}-${pkgver}" || return 1
  cp -a AUTHORS BUGS COPYING* INSTALL NEWS README* THANKS TODO \
    "$PKG/usr/doc/${pkgname}-${pkgver}" || return 1
  install -m0644 ../GRUB_configuration "$PKG/usr/doc/${pkgname}-${pkgver}/" || return 1
  cp -a build_i386-pc/docs/grub.html "$PKG/usr/doc/${pkgname}-${pkgver}/" || return 1
  if [ -r ChangeLog ]; then
    head -n 1000 ChangeLog > "$PKG/usr/doc/${pkgname}-${pkgver}/ChangeLog" || return 1
    touch -r ChangeLog "$PKG/usr/doc/${pkgname}-${pkgver}/ChangeLog" || return 1
  fi
}
