#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Based on Arch packaging; adapted for Slint.

pkgname=python3-scikit-build
_srcname=scikit-build
pkgver=0.18.1
pkgrel=1slint
arch=('noarch')
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (build system generator for Python extensions)"
"Scikit-build bridges setuptools and CMake for Python extension"
"modules written in C, C++, Cython, and Fortran."
)
url='https://scikit-build.readthedocs.io/'
license=('MIT')
depends=('cmake' 'python3' 'python3-packaging' 'python3-setuptools' 'python3-wheel')
makedepends=('git' 'python3-build' 'python3-installer' 'python3-hatchling' 'python3-hatch-vcs')
source=("https://github.com/scikit-build/scikit-build.git#tag=${pkgver}")
sha256sums=('SKIP')
options=('nosrcpack')

build() {
  cd "$SRC/${_srcname}" || return 1

  python3 -m build --wheel --no-isolation || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1

  install -Dm644 LICENSE "$PKG/usr/doc/$pkgname-$pkgver/LICENSE" || return 1
  if [[ -f README.rst ]]; then
    install -Dm644 README.rst "$PKG/usr/doc/$pkgname-$pkgver/README.rst" || return 1
  fi
}
