#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Jerome Leclanche <jerome@leclan.ch>
# Included in Slint and modified by:
# Didier Spaier <didier~at~slint~dot~fr>
_pkgname=humanize
pkgname=python3-humanize
pkgver=4.0.0
pkgrel=2slint
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Common humanization utilities for Python)"
)


url="https://github.com/jmoiron/humanize"
license=("MIT")
depends=("python3")
makedepends=("python3-setuptools")
source=("https://pypi.python.org/packages/source/${_pkgname:0:1}/$_pkgname/$_pkgname-$pkgver.tar.gz")
sha256sums=("a43f57115831ac7c70de098e6ac46ac13be00d69abbf60bdcac251344785bb19")
docs=("LICENCE" README.md)
arch=x86_64
build() {
	cd "$SRC/$_pkgname-$pkgver" || return 1
	python3 setup.py check || return 1
	rm -rf build
	python3 setup.py install --root="$PKG" || return 1
	mkdir -p "$PKG/usr/doc/${pkgname}-${pkgver}" || return 1
}
