#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libmspub
pkgver=0.1.4
pkgrel=1slint
url="https://wiki.documentfoundation.org/DLP/Libraries/libmspub"
source=("https://dev-www.libreoffice.org/src/libmspub/${pkgname}-${pkgver}.tar.xz")
docs=("AUTHORS" "COPYING.MPL" "ChangeLog" "NEWS" "README")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"libmspub (Microsoft Publisher import library)"
""
"libmspub is a library for parsing Microsoft Publisher"
"documents of all versions. It is part of the Document"
"Liberation Project and is based on librevenge."
""
"Homepage: https://wiki.documentfoundation.org/DLP/Libraries/libmspub"
)

build() {
  local doc_arg legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  case "${DOC:-0}" in
    0) doc_arg='--without-docs' ;;
    *) doc_arg='--with-docs' ;;
  esac

  # Keep the legacy compatibility fix for older toolchains.
  sed -i '/^#include <vector>$/a #include <stdint.h>' \
    src/lib/MSPUBMetaData.h || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --docdir="/usr/doc/$pkgname-$pkgver" \
    --build="$ARCH-slackware-linux" \
    "$doc_arg" || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG"/usr/lib*/*.la || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
