#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Packager: sektor

pkgname=pkgtools
pkgver=15.1
pkgrel=1slint
arch=noarch
# Rebuild this archive with ./make-manpages-l10n.sh <baseline-pkgtools.txz>.
source=("manpages-l10n.tar.xz")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"pkgtools (The Slackware package maintenance system)"
""
"This package contains utilities for handling Slackware packages."
"Included are the command line utilities 'installpkg', 'removepkg',"
"'makepkg', 'explodepkg', and 'upgradepkg' that install, remove,"
"build, examine, and upgrade software packages. Also included are"
"'pkgtool', a menu based program for installing packages, removing"
"packages, or viewing the packages that are installed on the system,"
"'pkgdiff', a utility for comparing two packages, documentation (man"
"pages), and a few other system admin scripts."
)

doinst() {
  # Migrate the package database from /var/log to /var/lib/pkgtools.
  for directory in packages scripts setup; do
    if [ ! -L "var/log/$directory" ] && [ ! -d "var/log/$directory" ]; then
      if [ -d "var/lib/pkgtools/$directory" ]; then
        (
          cd var/log || exit
          ln -sf "../lib/pkgtools/$directory" .
        )
      fi
    fi
  done

  for directory in removed_packages removed_scripts; do
    if [ ! -L "var/log/$directory" ] && [ ! -d "var/log/$directory" ]; then
      mkdir -p "var/log/pkgtools/$directory"
      (
        cd var/log || exit
        ln -sf "pkgtools/$directory" .
      )
    fi
    if [ ! -L "var/lib/pkgtools/$directory" ] && \
      [ ! -d "var/lib/pkgtools/$directory" ]; then
      mkdir -p var/lib/pkgtools
      (
        cd var/lib/pkgtools || exit
        ln -sf "../../log/pkgtools/$directory" .
      )
    fi
  done

  if [ ! -L var/log/packages ]; then
    if [ ! -d run/lock/pkgtools ]; then
      mkdir -p run/lock/pkgtools
    fi
    (
      flock 9 || exit 11
      while pidof tar >/dev/null 2>&1; do
        sleep 15
      done
      sleep 5

      mkdir -p var/log/pkgtools
      for directory in removed_packages removed_scripts; do
        if [ ! -d "var/log/pkgtools/$directory" ]; then
          mkdir -p "var/log/pkgtools/$directory"
          mv "var/log/$directory"/* "var/log/pkgtools/$directory" 2>/dev/null
          rm -rf "var/log/$directory"
          (
            cd var/log || exit
            ln -sf "pkgtools/$directory" .
          )
        fi
      done

      for directory in packages scripts setup; do
        mkdir -p "var/lib/pkgtools/$directory"
        mv "var/log/$directory"/* "var/lib/pkgtools/$directory" 2>/dev/null
        rm -rf "var/log/$directory"
        (
          cd var/log || exit
          ln -sf "../lib/pkgtools/$directory" .
        )
      done
    ) 9> run/lock/pkgtools/ldconfig.lock
  fi
}

build() {
  install -d "$PKG/usr/man/man8" || return 1
  for page in \
    explodepkg.8 \
    installpkg.8 \
    makepkg.8 \
    upgradepkg.8 \
    pkgdiff.8 \
    pkgtool.8 \
    removepkg.8; do
    install -m0644 "../manpages/$page" "$PKG/usr/man/man8/$page" || return 1
  done

  install -d "$PKG/usr/man" || return 1
  for page in manpages-l10n/*; do
    [ -f "$page" ] || continue
    manpage=$(basename "$page")
    lang=${manpage%%.*}
    install -d "$PKG/usr/man/$lang/man8" || return 1
    install -m0644 "$page" "$PKG/usr/man/$lang/man8/${manpage#*.}.8" || return 1
  done

  install -d "$PKG/sbin" || return 1
  for file in explodepkg installpkg makepkg pkgdiff pkgtool removepkg \
    upgradepkg; do
    install -m0755 "../scripts/$file" "$PKG/sbin/$file" || return 1
  done

  install -d \
    "$PKG/var/lib/pkgtools/packages" \
    "$PKG/var/lib/pkgtools/scripts" \
    "$PKG/var/lib/pkgtools/douninst.sh" \
    "$PKG/var/log/pkgtools/removed_packages" \
    "$PKG/var/log/pkgtools/removed_scripts" || return 1
}
