#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=efibootmgr
pkgver=18
pkgrel=1slint
url="https://github.com/rhboot/efibootmgr"
source=("https://github.com/rhboot/efibootmgr/archive/refs/tags/${pkgver}.tar.gz")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"efibootmgr (tool to modify UEFI boot entries)"
""
"efibootmgr is a Linux userspace application to modify the Intel"
"Extensible Firmware Interface (EFI) Boot Manager. This application"
"can create and destroy boot entries, change the boot order, change"
"the next running boot option, and more."
""
"Homepage: https://github.com/rhboot/efibootmgr"
)

license=("GPL2")
depends=("glibc" "popt")
makedepends=("efivar")
docs=("AUTHORS" "COPYING*" "INSTALL" "README*" "TODO*")

build() {
  cd "${pkgname}-${pkgver}" || return 1

  export EFIDIR=/boot/efi
  export CFLAGS="${CFLAGS:-$SLKCFLAGS} -Wno-pointer-sign"

  make mandir=/usr/man || return 1
  make install mandir=/usr/man DESTDIR="$PKG" || return 1
}
