#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-LWP-Protocol-https
pkgver=6.10
pkgrel=1slint
export srcname=LWP-Protocol-https
source=("https://cpan.metacpan.org/authors/id/O/OA/OALDERS/$srcname-$pkgver.tar.gz")
docs=("Changes")
url="https://metacpan.org/pod/LWP::Protocol::https"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-LWP-Protocol-https (https support for libwww-perl)"
"It provides HTTPS protocol support for LWP::UserAgent."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
