#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

pkgname=gst-plugins-bad-free
srcname=gst-plugins-bad
export srcname
pkgver=1.28.1
pkgrel=1slint
url="https://gstreamer.freedesktop.org/"
license=("LGPL-2.1-or-later")
source=("https://gstreamer.freedesktop.org/src/gst-plugins-bad/${srcname}-${pkgver}.tar.xz")
options=("nosrcpack")
docs=("AUTHORS*" "COPYING*" "NEWS*" "README*" "RELEASE*")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"gst-plugins-bad-free (bad set of GStreamer plugins)"
""
"GStreamer Bad Plug-ins are a set of plug-ins that are not as"
"well tested or polished as the Good set."
"This package keeps the freely distributable subset used in Slint."
)

build() {
  local docsDir

  docsDir="$PKG/usr/doc/$pkgname-$pkgver"

  cd "$SRC/$srcname-$pkgver" || return 1

  meson setup buildDir \
    --prefix=/usr \
    --libdir="lib${LIBDIRSUFFIX}" \
    --libexecdir=/usr/libexec \
    --bindir=/usr/bin \
    --sbindir=/usr/sbin \
    --includedir=/usr/include \
    --datadir=/usr/share \
    --mandir=/usr/man \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Dbenchmarks=disabled \
    -Dexamples=disabled \
    -Dgpl=disabled \
    -Ddvbsuboverlay=disabled \
    -Ddvdspu=disabled \
    -Dsiren=disabled || return 1

  meson compile -C buildDir -j "$numjobs" || return 1
  DESTDIR="$PKG" meson install -C buildDir || return 1

  install -Dm0644 "$SRC/../SLKBUILD" "$docsDir/SLKBUILD" || return 1
}
