#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Librewish <librewish@gail.com>
# Contributor: Levente Polyak <anthraxx[at]archlinux[dot]org>
# Contributor: Timothy Redaelli <timothy.redaelli@gmail.com>
# Contributor: darkcoder <mario_vazq@hotmail.com>
# Included in Slint by Didier Spaier didieratslintdotfr
pkgname=os-prober
pkgver=1.81
pkgrel=2slint
url="http://joey.kitenet.net/code/os-prober/"
arch=('x86_64')
slackdesc=(\
"os-prober (an OS detector)"
"os-prober detects OSes on other partitions than the current system"
"partition, and outputs the results in a generic machine-readable"
"format. This information can be used to add other OSes to the boot")
license=('GPL3')
provides=('os-prober' 'os-prober-garuda')
#Homepage: http://packages.debian.org/unstable/utils/os-proberconflicts=('os-prober' 'os-prober-garuda')
#replaces=('os-prober-garuda')
options=('nosrcpack')
source=(http://deb.debian.org/debian/pool/main/o/os-prober/os-prober_1.81.tar.xz
    os-prober-frugalware.diff
	os-prober-mdraidfix.patch
	os-prober-btrfsfix.patch
	os-prober-bootpart-name-fix.patch
	os-prober-mounted-partitions-fix.patch
	os-prober-factor-out-logger.patch
	os-prober-factored-logger-efi-fix.patch
	os-prober-umount-fix.patch
	os-prober-grepfix.patch
	fix-blkid-path.patch
	grub-initrd-generation-fix
	grub-initrd-generation-fix.hook)

build() {
  cd "${pkgname}-${pkgver}" || return 1

  patch -p1 --verbose -i "$SRC"/os-prober-frugalware.diff || exit 1
  patch -p1 --verbose -i "$SRC"/os-prober-mdraidfix.patch || exit 1
  patch -p1 --verbose -i "$SRC"/os-prober-btrfsfix.patch || exit 1
  patch -p1 --verbose -i "$SRC"/os-prober-bootpart-name-fix.patch || exit 1
  patch -p1 --verbose -i "$SRC"/os-prober-mounted-partitions-fix.patch || exit 1
  patch -p1 --verbose -i "$SRC"/os-prober-factor-out-logger.patch || exit 1
  patch -p1 --verbose -i "$SRC"/os-prober-factored-logger-efi-fix.patch || exit 1
  patch -p1 --verbose -i "$SRC"/os-prober-umount-fix.patch || exit 1
#  patch -p1 --verbose -i "$SRC"/os-prober-grub2-parsefix.patch || exit 1
#  patch -p1 --verbose -i "$SRC"/os-prober-grub2-multiple-images.patch || exit 1
  patch -p1 --verbose -i "$SRC"/os-prober-grepfix.patch || exit 1
#  patch -p1 --verbose -i "$SRC"/os-prober-gentoo-fix.patch || exit 1
  patch -p1 --verbose -i "$SRC"/fix-blkid-path.patch || exit 1

  # adjust lib dir to allow detection of 64-bit distros
  sed -i -e "s:/lib/ld\*\.so\*:/lib*/ld*.so*:g" os-probes/mounted/common/90linux-distro
  rm -f Makefile
  make newns || return 1

  install -Dm644 \
    "$SRC/grub-initrd-generation-fix.hook" \
    "$PKG/usr/share/libalpm/hooks/grub-initrd-generation-fix.hook" || return 1
  install -Dm755 \
    "$SRC/grub-initrd-generation-fix" \
    "$PKG/usr/share/libalpm/scripts/grub-initrd-generation-fix" || return 1

  install -Dm755 os-prober "${PKG}/usr/bin/os-prober" || return 1
  install -Dm755 linux-boot-prober "${PKG}/usr/bin/linux-boot-prober" || return 1
  install -Dm755 newns "${PKG}/usr/lib/os-prober/newns" || return 1
  install -Dm755 common.sh "${PKG}/usr/share/os-prober/common.sh" || return 1

  for dir in os-probes os-probes/mounted os-probes/init linux-boot-probes linux-boot-probes/mounted; do
    install -dm 755 "${PKG}/usr/lib/${dir}"
    install -m 755 -t "${PKG}/usr/lib/${dir}" "${dir}"/common/*
    [[ -d "${dir}"/x86 ]] && cp -r "${dir}"/x86/* "${PKG}/usr/lib/${dir}"
  done

  install -Dm 755 os-probes/mounted/powerpc/20macosx "${PKG}"/usr/lib/os-probes/mounted/20macosx
  install -dm 755 "${PKG}"/var/lib/os-prober
}
