.\" mb-applet-clock.1
.\" Copyright 2004  Moray Allan
.TH mb-applet-clock 1 "Jul 17 2004" ""
.SH NAME
mb-applet-clock \- a clock panel applet
.SH SYNOPSIS
.B mb-applet-clock
.SH DESCRIPTION
.B mb-applet-clock
is a panel applet which displays the current time.

Matchbox is a base environment for the X Window System running on non-desktop
embedded platforms such as handhelds, set-top boxes, kiosks and anything else
for which screen space, input mechanisms or system resources are limited.

.SH AUTHOR
.B mb-applet-clock
was written by Matthew Allum <mallum@o-hand.com>.

