.\" mb-applet-wireless.1
.\" Copyright 2004  Moray Allan
.TH mb-applet-wireless 1 "Jul 17 2004" ""
.SH NAME
mb-applet-wireless \- a wireless monitor panel applet
.SH SYNOPSIS
.B mb-applet-wireless
.SH DESCRIPTION
.B mb-applet-wireless
is a panel applet which displays the wireless networking signal strength.
At maximum signal strength four bars are shown lit up brightly, while at minimum strength
the four bars are all shown dimmed out.

Matchbox is a base environment for the X Window System running on non-desktop
embedded platforms such as handhelds, set-top boxes, kiosks and anything else
for which screen space, input mechanisms or system resources are limited.
.SH AUTHOR
.B mb-applet-wireless
was written by Matthew Allum <mallum@o-hand.com>.

