.\" mb-applet-menu-launcher.1
.\" Copyright 2004  Moray Allan
.TH mb-applet-menu-launcher 1 "Jul 17 2004" ""
.SH NAME
mb-applet-menu-launcher \- a launcher menu panel applet
.SH SYNOPSIS
.B mb-applet-menu-launcher
[\fIoptions\fR]
.SH DESCRIPTION
.B mb-applet-menu-launcher
is a panel applet which provides a menu of applications installed on
the system. Applications can be launched by choosing them from the menu.

Matchbox is a base environment for the X Window System running on non-desktop
embedded platforms such as handhelds, set-top boxes, kiosks and anything else
for which screen space, input mechanisms or system resources are limited.
.SH OPTIONS
.TP
.B \-display
X display to connect to
.SH AUTHOR
.B mb-applet-menu-launcher
was written by Matthew Allum <mallum@o-hand.com>.

