/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __NLD_MARSHAL_MARSHAL_H__
#define __NLD_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:STRING (./nld-marshal.list:1) */
#define nld_marshal_VOID__STRING	g_cclosure_marshal_VOID__STRING


G_END_DECLS

#endif /* __NLD_MARSHAL_MARSHAL_H__ */
