#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=gperf
pkgver=3.3
pkgrel=2slint
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"gperf (a perfect hash function generator)"
""
"gperf is a perfect hash function generator written in C++."
"It transforms a user-specified keyword set into a perfect hash"
"function. gperf generates keyword recognizers for lexical"
"analyzers in several production and research compilers and"
"language processing tools."
""
""
""
)
url="https://www.gnu.org/software/gperf/"
license=("GPL3")
source=("https://ftp.gnu.org/gnu/gperf/${pkgname}-${pkgver}.tar.gz")

build() {
  local docDir

  cd "${pkgname}-${pkgver}" || return 1

  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/man \
    --infodir=/usr/info \
    --docdir=/usr/doc/${pkgname}-${pkgver} \
    --build="${ARCH}-slackware-linux" || return 1

  make -j"$numjobs" || make || return 1
  make DESTDIR="$PKG" install || return 1

  rm -f "$PKG/usr/info/dir" || return 1

  docDir="$PKG/usr/doc/${pkgname}-${pkgver}"
  install -d "$docDir" || return 1
  cp -a AUTHORS* COPYING* INSTALL* JOIN-GNU* NEWS* README* "$docDir/" || return 1
  if [ -r ChangeLog ]; then
    head -n 1000 ChangeLog > "$docDir/ChangeLog" || return 1
    touch -r ChangeLog "$docDir/ChangeLog" || return 1
  fi
}
