#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-IO-Socket-SSL
pkgver=2.074
pkgrel=1slint
export srcname=IO-Socket-SSL
source=("https://cpan.metacpan.org/authors/id/S/SU/SULLR/$srcname-$pkgver.tar.gz")
docs=("BUGS" "Changes" "README")
url="https://metacpan.org/pod/IO::Socket::SSL"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-IO-Socket-SSL (SSL wrapper for IO::Socket::INET)"
"IO::Socket::SSL is a drop-in SSL-enabled replacement"
"for IO::Socket::INET."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  yes | perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN1DIR=/usr/man/man1 \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
