#!/bin/bash
# shellcheck shell=bash disable=SC2034

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=xvidcore
pkgver=1.3.7
pkgrel=1slint
url="https://labs.xvid.com/project/"
source=("https://downloads.xvid.com/downloads/${pkgname}-${pkgver}.tar.gz")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"xvidcore (MPEG-4 compliant video codec)"
"Xvid is an ISO MPEG-4 compliant video codec and free software"
"library."
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname/build/generic" || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-static \
    --build="$ARCH-slackware-linux" || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG"/{,usr/}lib"${LIBDIRSUFFIX}"/*.la
  rm -f "$PKG"/{,usr/}lib"${LIBDIRSUFFIX}"/*.a

  cd "$SRC/$pkgname" || return 1
  install -d "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  cp -a AUTHORS ChangeLog* CodingStyle LICENSE README TODO doc \
    "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
