#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=flac
pkgver=1.3.4
pkgrel=2slint
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"flac (Free Lossless Audio Codec)"
""
"FLAC stands for Free Lossless Audio Codec. It is similar to MP3,"
"but lossless. The stream format is in the public domain, and"
"neither the FLAC format nor its implemented encoding and decoding"
"methods are covered by any patent."
"The sources for libFLAC and libFLAC++ are available under the LGPL,"
"while flac, metaflac, and the plugins are available under the GPL."
""
""
)
url="https://xiph.org/flac/"
license=("GPL2" "LGPL2.1")
source=(
  "https://downloads.xiph.org/releases/flac/${pkgname}-${pkgver}.tar.xz"
  "flac.man.diff.gz"
)

build() {
  local disableAsmOptimizations

  cd "${pkgname}-${pkgver}" || return 1

  zcat ../flac.man.diff.gz | patch -p1 --verbose --backup --suffix=.orig || return 1

  if [ "$ARCH" != "x86_64" ]; then
    disableAsmOptimizations="--disable-asm-optimizations"
  else
    disableAsmOptimizations=""
  fi

  ./configure \
    --prefix=/usr \
    --libdir=/usr/lib"${LIBDIRSUFFIX}" \
    --mandir=/usr/man \
    --docdir=/usr/doc/${pkgname}-${pkgver} \
    --disable-silent-rules \
    ${disableAsmOptimizations} \
    --build="${ARCH}-slackware-linux" || return 1

  make -j"$numjobs" || make || return 1
  make DESTDIR="$PKG" install || return 1

  rm -f "$PKG"/lib"${LIBDIRSUFFIX}"/*.la "$PKG"/usr/lib"${LIBDIRSUFFIX}"/*.la || return 1

  if [ -d "$PKG/usr/share/doc" ]; then
    mv "$PKG/usr/share/doc" "$PKG/usr" || return 1
  fi
  if [ -e "$PKG/usr/doc/${pkgname}-${pkgver}/FLAC.tag" ]; then
    rm "$PKG/usr/doc/${pkgname}-${pkgver}/FLAC.tag" || return 1
  fi
  if [ -d "$PKG/usr/doc/${pkgname}-${pkgver}/html" ]; then
    mv "$PKG/usr/doc/${pkgname}-${pkgver}/html/"* "$PKG/usr/doc/${pkgname}-${pkgver}/" || return 1
    rmdir "$PKG/usr/doc/${pkgname}-${pkgver}/html" || return 1
  fi
  if [ -d "$PKG/usr/doc/${pkgname}-${pkgver}/api" ]; then
    rm -rf "$PKG/usr/doc/${pkgname}-${pkgver}/api/"* || return 1
    cat > "$PKG/usr/doc/${pkgname}-${pkgver}/api/README" <<'EOF' || return 1
Full HTML based API documentation may be found in the FLAC source
archive. It is not included in the binary package due to its size.
EOF
  fi
  cp -a AUTHORS COPYING* README "$PKG/usr/doc/${pkgname}-${pkgver}/" || return 1
}
