#!/usr/bin/env bash
set -euo pipefail

scriptDir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)

# Keep this list in build order. Add more category/package entries as needed.
packageList=(
  "d/python3"
  "d/python3-setuptools"
  "d/python3-pip"
  "l/python-build"
  "l/python-wheel3.11"
  "l/python-installer3.11"
  "l/python-click"
  "l/python-toml"
  "l/python-idna"
  "l/python-requests"
  "l/python-attrs"
  "l/python-automat"
  "l/python-constantly"
  "l/python-incremental"
  "l/python-pyasn1"
  "k/python-pyasn1-modules"
  "l/python-service-identity"
  "ap/python-hkdf"
  "l/python-humanize"
  "l/python-hyperlink"
  "l/python-openssl"
  "l/python-pynacl"
  "l/python-txaio"
  "l/python-wsaccel"
  "l/python-tqdm"
  "l/python-spake2"
  "l/python-twisted"
  "l/python-autobahn"
  "l/python-txtorcon"
  "l/python-daemonize"
  "l/python-evdev"
  "l/python-ptyprocess"
  "l/python-pexpect"
  "l/python-pyenchant"
  "l/pyperclip"
  "l/python-pyte"
  "l/python-wcwidth"
  "l/python-pyudev"
  "l/python-semantic-version"
  "l/python-setuptools-rust"
  "l/python-setuptools_scm3.11"
  "l/python-numpy"
  "l/python3-setproctitle"
  "l/python-tomli3.11"
  "l/pyparsing3.11"
  "l/python-importlib_metadata3.11"
  "l/dbus-python3.11"
  "l/pycairo3.11"
  "l/pygobject3.11"
  "l/python3-dasbus"
  "d/speech-dispatcher3.11"
  "l/speech-dispatcher"
  "xap/fontforge"
  "xap/orca"
  "xap/cthulhu"
  "ap/magic-wormhole"
  "ap/fenrir"
)

for packagePath in "${packageList[@]}"; do
  printf 'Building %s\n' "$packagePath"
  "$scriptDir/build-package.sh" --skip-staged --only "$packagePath"
done
