#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packaged for Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=tesseract-data
pkgver=4.0.0
pkgrel=9slint
options=(nosrcpack)
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Language data for Tesseract Open Source OCR Engine)"
"This package contains the per language data for Tesseract." 
"The lead developer is Ray Smith. The maintainer is Zdenko Podobny."
)

doinst() {
	(
	cd usr/share/tessdata || exit 1
	ln -sf Latin.traineddata eng.traineddata
	)
}

# The source archive contents selected files taken from:
# https://github.com/tesseract-ocr/tessdata_fast/tree/4.0.0/script

source=("https://github.com/tesseract-ocr/tessdata_fast/archive/refs/tags/${pkgver}.tar.gz" README.md SLKBUILD COPYING)

docs=(SLKBUILD COPYING)

build() {
	cd "$SRC/tessdata_fast-$pkgver/script" || return 1
	mkdir -p "$PKG/usr/share/tessdata" || return 1
	cp -p ./* "$PKG/usr/share/tessdata/" || return 1
	mkdir -p "$PKG/usr/doc/${pkgname}-$pkgver" || return 1
	pandoc -s -f gfm "$SRC/README.md" -o "$PKG/usr/doc/${pkgname}-$pkgver/README.html" || return 1
	(
	 cd "$startdir/pkg/usr/share/tessdata" || exit 1
	 ln -s Latin.traineddata eng.traineddata
	) || return 1
}
