.\" matchbox-session.1
.\" Copyright 2004  Moray Allan
.TH matchbox-session 1 "Jul 16 2004" ""
.SH NAME
matchbox-session \- Matchbox session manager
.SH SYNOPSIS
.B matchbox-session
.SH DESCRIPTION
.B matchbox-session
is a simple X session manager for the Matchbox Project.

Matchbox is a base environment for the X Window System running on non-desktop
embedded platforms such as handhelds, set-top boxes, kiosks and anything else
for which screen space, input mechanisms or system resources are limited.

.SH FILES
.TP
.I /etc/matchbox/session
System-wide default Matchbox session script
.TP
.I ~/.matchbox/session
Per-user Matchbox session script

.SH AUTHOR
.B matchbox-session
was written by Matthew Allum <mallum@o-hand.com>.

