.\" matchbox-desktop.1
.\" Copyright 2004  Moray Allan
.TH matchbox-desktop 1 "Jul 17 2004" ""
.SH NAME
matchbox-desktop \- a desktop application launcher for resource-limited systems
.SH SYNOPSIS
.B matchbox-desktop
[\fIoptions\fR]
.SH DESCRIPTION
.B matchbox-desktop
uses the desktop background to provide an application
launcher. It reads the standard desktop entry specification files also used
by GNOME and KDE to discover the applications available on the system.

Matchbox is a base environment for the X Window System running on non-desktop
embedded platforms such as handhelds, set-top boxes, kiosks and anything else
for which screen space, input mechanisms or system resources are limited.

.SH AUTHOR
.B matchbox-desktop
was written by Matthew Allum <mallum@o-hand.com>.

