#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-Test-RequiresInternet
pkgver=0.05
pkgrel=2slint
export srcname=Test-RequiresInternet
source=("https://cpan.metacpan.org/authors/id/M/MA/MALLEN/$srcname-$pkgver.tar.gz")
docs=("Changes" "README")
url="https://metacpan.org/pod/Test::RequiresInternet"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-Test-RequiresInternet (easily test connectivity)"
"It checks internet connectivity before network tests"
"run against remote resources."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
