#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-YAML-Tiny
pkgver=1.73
pkgrel=2slint
export srcname=YAML-Tiny
source=("https://cpan.metacpan.org/authors/id/E/ET/ETHER/$srcname-$pkgver.tar.gz")
docs=("Changes" "INSTALL" "LICENSE" "README")
url="https://metacpan.org/pod/YAML::Tiny"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-YAML-Tiny (minimal YAML reader/writer for simple data files)"
"Implements a compact subset of YAML focused on straightforward cases."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  # Keep existing package behavior: install without running upstream tests.
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
