#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python3-autobahn
_srcname=autobahn
pkgver=22.2.2
pkgrel=2slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (WebSocket and WAMP for Python)"
""
"Autobahn|Python provides open source implementations of"
"the WebSocket Protocol and the Web Application Messaging"
"Protocol (WAMP) for Python."
""
"Homepage: https://crossbar.io/autobahn/"
)
url="https://crossbar.io/autobahn/"
depends=("python3")
makedepends=("python3-setuptools")
source=("https://files.pythonhosted.org/packages/source/a/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  rm -rf build || return 1
  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  install -m 0644 LICENSE "$docdir/LICENSE" || return 1
  install -m 0644 README.rst "$docdir/README.rst" || return 1
}
