#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=zvbi
pkgver=0.2.35
pkgrel=2slint
source=("https://downloads.sourceforge.net/project/zapping/zvbi/${pkgver}/${pkgname}-${pkgver}.tar.bz2")
url="http://zapping.sourceforge.net/ZVBI/"
license=("GPL")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"zvbi (Zapping VBI library)"
""
"ZVBI provides functions to capture and decode VBI data."
"It is written in plain ANSI C with few dependencies on other"
"tools and libraries, licensed under GPL."
""
"Homepage: http://zapping.sourceforge.net/ZVBI/"
)

build() {
  cd "$SRC/$pkgname-$pkgver" || return 1

  CFLAGS="$SLKCFLAGS" \
  CXXFLAGS="$SLKCFLAGS" \
  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/man \
    --docdir="/usr/doc/$pkgname-$pkgver" \
    --enable-static=no \
    --build="$ARCH-slackware-linux" || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG/usr/lib${LIBDIRSUFFIX}"/*.la || return 1

  install -d "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  cp -a ABOUT-NLS AUTHORS BUGS COPYING COPYING.LIB ChangeLog INSTALL NEWS README TODO \
    "$PKG/usr/doc/$pkgname-$pkgver/" || return 1
  install -Dm0644 "$startdir/SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.SlackBuild" || return 1
}
