#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python-configparser
_srcname=configparser
pkgver=5.2.0
pkgrel=2slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (backport of the Python 3 configparser module)"
""
"configparser backports the updated Python 3 configparser"
"module for use outside the standard library."
""
"Homepage: https://docs.python.org/3/library/configparser.html"
)
url="https://docs.python.org/3/library/configparser.html"
depends=("python")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/c/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  sed -i "/^\[metadata\]/a version = $pkgver" setup.cfg || return 1
  sed -i '/^\[tool\.setuptools_scm\]/,/^$/d' pyproject.toml || return 1

  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  install -m 0644 PKG-INFO "$docdir/PKG-INFO" || return 1
  install -m 0644 README.rst "$docdir/README.rst" || return 1
}
