#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python3-attrs
srcname=attrs
export srcname
pkgver=21.4.0
pkgrel=2slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (attributes without boilerplate)"
""
"attrs is an MIT-licensed Python package with class decorators"
"that ease the chores of implementing the most common"
"attribute-related object protocols."
""
"Homepage: https://pypi.org/project/attrs/"
)
url="https://pypi.org/project/attrs/"
depends=("python")
depends=("python3")
makedepends=("python3-setuptools")
source=("https://files.pythonhosted.org/packages/source/a/${srcname}/${srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  local docDir

  cd "$SRC/${srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docDir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docDir" || return 1

  shopt -s nullglob
  for doc in LICENSE *.rst docs; do
    [[ -e $doc ]] || continue
    cp -a "$doc" "$docDir/" || return 1
  done
  shopt -u nullglob

  if [[ -d $docDir/docs ]]; then
    find "$docDir/docs" -type f -exec chmod 0644 {} + || return 1
  fi
}
