#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=mpv
pkgver=0.41.0
pkgrel=1slint
source=(
  "https://github.com/mpv-player/mpv/archive/refs/tags/v${pkgver}.tar.gz"
)
url="https://github.com/mpv-player/mpv"
license=("GPL2")
makedepends=("meson" "ninja" "python3")
docs=("Copyright*" "LICENSE*" "README*" "RELEASE_NOTES*")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"mpv (a command-line media player)"
""
"mpv is a free (as in freedom) media player for the command line. It"
"supports a wide variety of media file formats, audio and video codecs,"
"and subtitle types. Powerful scripting capabilities can make the"
"player do almost anything. While mpv strives for minimalism and"
"provides no real GUI, it has a small controller on top of the video"
"for basic control."
""
"Homepage: https://mpv.io/"
)

doinst() {
  config() {
    local newConfig oldConfig
    newConfig="$1"
    oldConfig="$(dirname "$newConfig")/$(basename "$newConfig" .new)"

    if [ ! -r "$oldConfig" ]; then
      mv "$newConfig" "$oldConfig"
    elif [ "$(md5sum < "$oldConfig")" = "$(md5sum < "$newConfig")" ]; then
      rm "$newConfig"
    fi
  }

  for configFile in etc/mpv/*.conf.new; do
    config "$configFile"
  done

  if [ -x /usr/bin/update-desktop-database ]; then
    /usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
  fi

  if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
    if [ -x /usr/bin/gtk-update-icon-cache ]; then
      /usr/bin/gtk-update-icon-cache -f usr/share/icons/hicolor >/dev/null 2>&1
    fi
  fi
}

build() {
  cd "$SRC/$pkgname-$pkgver" || return 1

  meson setup \
    --prefix=/usr \
    "--libdir=lib${LIBDIRSUFFIX}" \
    --libexecdir=/usr/libexec \
    --bindir=/usr/bin \
    --sbindir=/usr/sbin \
    --includedir=/usr/include \
    --datadir=/usr/share \
    --mandir=/usr/man \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Dmanpage-build=enabled \
    -Dlibmpv=true \
    -Dcdda=enabled \
    -Ddvdnav=enabled \
    -Ddvbin=enabled \
    -Dcplugins=enabled \
    -Diconv=enabled \
    -Dlibarchive=enabled \
    -Dlibbluray=enabled \
    -Dsdl2=enabled \
    -Dgl-x11=enabled \
    -Dsdl2-gamepad=enabled \
    -Dpulse=enabled \
    -Dpipewire=enabled \
    -Dsdl2-audio=enabled \
    -Dopenal=enabled \
    -Dlua=luajit \
    -Djavascript=enabled \
    meson-build || return 1

  # numjobs is intentionally expanded as a make-style argument list.
  # shellcheck disable=SC2086
  meson compile -C meson-build -j $numjobs || return 1
  DESTDIR="$PKG" meson install -C meson-build || return 1

  rm -rf "$PKG/usr/share/doc"

  install -d "$PKG/etc/mpv" || return 1
  cp -a etc/*.conf "$PKG/etc/mpv/" || return 1
  install -d "$PKG/usr/doc/$pkgname-$pkgver" || return 1

  for configFile in "$PKG"/etc/mpv/*; do
    mv "$configFile" "${configFile}.new" || return 1
  done

  for docPath in DOCS/*.md DOCS/*.rst DOCS/*.txt; do
    [ -e "$docPath" ] || continue
    cp -a "$docPath" "$PKG/usr/doc/$pkgname-$pkgver/" || return 1
  done
}
