#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python-pytz
_srcname=pytz
pkgver=2021.3
pkgrel=2slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (world timezone definitions for Python)"
""
"python-pytz brings the Olson timezone database into Python"
"for accurate, cross-platform timezone calculations."
""
"Homepage: https://launchpad.net/pytz"
)
url="https://launchpad.net/pytz"
depends=("python")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/p/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  install -m 0644 LICENSE.txt "$docdir/LICENSE.txt" || return 1
  install -m 0644 PKG-INFO "$docdir/PKG-INFO" || return 1
  install -m 0644 README.rst "$docdir/README.rst" || return 1
}
