#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Added in Slint Python 3.11 migration

pkgname=python3-pycparser
srcname=pycparser
export srcname
pkgver=2.23
pkgrel=2slint
slackdesc="$pkgname (C parser in Python 3)"
url="https://github.com/eliben/pycparser"
license=("BSD-3-Clause")
arch=("x86_64")
depends=("python3")
makedepends=("python3-setuptools")
source=("https://files.pythonhosted.org/packages/source/p/pycparser/pycparser-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  local docDir
  local docFile

  docDir="$PKG/usr/doc/$pkgname-$pkgver"

  cd "$SRC/${srcname}-${pkgver}" || return 1
  python3 setup.py install --root="$PKG" || return 1

  install -d "$docDir" || return 1
  for docFile in LICENSE *.md *.rst examples; do
    [[ -e "$docFile" ]] || continue
    cp -a "$docFile" "$docDir/" || return 1
  done
}
