#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Antonio Rojas <arojas@archlinux.org>
# Contributor: Ashwin Vishnu <ashwinvis+arch at pr0t0nm4il dot com>
# Contributor: xantares
# Included in Slint by Didier Spaier didieratslintdotfr
pkgname=python3-pythran
export srcname=pythran
pkgver=0.11.0
pkgrel=1slint
slackdesc="$pkgname (Ahead of Time compiler for numeric kernels)"
url='https://pythran.readthedocs.io/'
license=(BSD)
depends=(python-networkx python-ply python3-numpy python-beniget python3-six xsimd boost)
makedepends=(python3-setuptools python-pytest-runner)
source=(https://files.pythonhosted.org/packages/source/p/pythran/pythran-$pkgver.tar.gz)
sha256sums=('0b2cba712e09f7630879dff69f268460bfe34a6d6000451b47d598558a92a875')
docs=(AUTHORS LICENSE README.rst)
build() {
  export PYTHONPATH="usr/lib64/python3.11/site-packages"
  cd "$SRC/${srcname}-$pkgver" || return 1
  python3 setup.py build || return 1
  python3 setup.py install --root="$PKG" --optimize=1 --skip-build || return 1
  rm -rf "$PKG"/usr/lib64/python*/site-packages/pythran/boost
  rm -rf "$PKG"/usr/lib64/python*/site-packages/pythran/xsimd
}
