#!/bin/bash
# shellcheck shell=bash disable=SC2034

pkgname=python3-pythran
export srcname=pythran
pkgver=0.18.1
pkgrel=1slint
slackdesc="$pkgname (Ahead of Time compiler for numeric kernels)"
url='https://pythran.readthedocs.io/'
license=(BSD)
depends=(python3-ply python3-numpy python-beniget python-gast python3-six xsimd boost)
makedepends=(python3-setuptools)
source=("https://files.pythonhosted.org/packages/source/p/${srcname}/${srcname}-${pkgver}.tar.gz")
sha256sums=('8803ed948bf841a11bbbb10472a8ff6ea24ebd70e67c3f77b77be3db900eccfe')
docs=(AUTHORS LICENSE README.rst)
build() {
  cd "$SRC/${srcname}-$pkgver" || return 1
  python3 setup.py build || return 1
  python3 setup.py install --root="$PKG" --optimize=1 --skip-build || return 1
  rm -rf "$PKG"/usr/lib*/python*/site-packages/pythran/{boost,xsimd}
}
