#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Maintained in Slint by Didier Spaier didieratslintdotfr

pkgname=libpeas
pkgver=1.30.0
pkgrel=1slint
url="https://wiki.gnome.org/Projects/Libpeas"
license=("LGPL-2.1-or-later")
source=("https://download.gnome.org/sources/$pkgname/${pkgver%.*}/$pkgname-$pkgver.tar.xz")
docs=("AUTHORS" "COPYING" "NEWS" "README")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (GObject plugin system)"
""
"Libpeas is a GObject-based plugin engine that gives applications"
"extensibility with multiple extension points and optional language"
"support for C, Python, and JavaScript plugins."
)

doinst() {
  if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
    if [ -x /usr/bin/gtk-update-icon-cache ]; then
      /usr/bin/gtk-update-icon-cache -f usr/share/icons/hicolor >/dev/null 2>&1
    fi
  fi
}

build() {
  local source_dir pkg_root legacy_doc

  source_dir="$SRC/$pkgname-$pkgver"
  pkg_root="$(dirname "$SRC")"
  legacy_doc="$PKG/usr/doc/$pkgname-$pkgver/${pkgname}.Slack""Build"

  rm -rf build || return 1
  cd "$source_dir" || return 1

  meson setup build . \
    --buildtype=release \
    -Dglade_catalog=false \
    --infodir=/usr/info \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --localstatedir=/var \
    --mandir=/usr/man \
    --prefix=/usr \
    --sysconfdir=/etc || return 1

  ninja -C build -j "$numjobs" || return 1
  DESTDIR="$PKG" ninja -C build install || return 1

  install -Dm644 "$pkg_root/SLKBUILD" "$legacy_doc" || return 1
}
