The package i3 contains the i3 windows manager, including the script i3-config-wizard
automatically started if the file ~/.config/i3/config does not exist, allowing users to
configure i3 to their liking.

Alternatively, blind users can run the script i38, included in the I38 package, that brings
features accessible with speech and braille to i3, and also help configure it to their liking.

This packages includes these programs:
i3
i3-config-wizard
i3-dmenu-desktop
i3-dump-log
i3-input
i3-migrate-config-to-v4
i3-msg
i3-nagbar
i3-save-tree
i3-sensible-editor
i3-sensible-pager
i3-sensible-terminal
i3bar

and also these man pages (type "man <page name>" to use them):

i3-config-wizard
i3-dmenu-desktop
i3-dump-log
i3-input
i3-migrate-config-to-v4
i3-msg
i3-nagbar
i3-save-tree
i3-sensible-editor
i3-sensible-pager
i3-sensible-terminal
i3
i3bar

More documentation is available in subdirectories of /usr/doc/i3-4.24/ in text and html formats.
