#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=yelp-tools
pkgver=42.1
pkgrel=1slint
url="https://wiki.gnome.org/Apps/Yelp"
source=("https://download.gnome.org/sources/${pkgname}/${pkgver%.*}/${pkgname}-${pkgver}.tar.xz")
options=("nosrcpack")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"yelp-tools (documentation checker)"
"yelp-tools is a set of command-line tools to build and check"
"documentation."
""
"Homepage: https://wiki.gnome.org/Apps/Yelp"
)

build() {
  local docDir legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"
  docDir="$PKG/usr/doc/$pkgname-$pkgver"

  cd "$SRC/$pkgname-$pkgver" || return 1

  meson setup \
    --buildtype=release \
    --infodir=/usr/info \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --localstatedir=/var \
    --mandir=/usr/man \
    --prefix=/usr \
    -Dhelp=true \
    --sysconfdir=/etc \
    build || return 1
  meson compile -C build || return 1
  meson install -C build --destdir "$PKG" || return 1

  mkdir -p "$docDir" || return 1
  cp -a AUTHORS COPYING* NEWS README.md "$docDir" || return 1
  find "$docDir" -type f -exec chmod 0644 {} \; || return 1
  install -Dm0644 "$SRC/../SLKBUILD" "$docDir/$legacyDocName" || return 1
}
