#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-Gtk3
pkgver=0.038
pkgrel=1slint
depends=("perl-Glib-Object-Introspection" "perl-Cairo-GObject")
export srcname=Gtk3
source=("https://cpan.metacpan.org/authors/id/X/XA/XAOC/$srcname-$pkgver.tar.gz")
docs=("NEWS" "README*")
url="https://metacpan.org/pod/Gtk3"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-Gtk3 (Perl interface to GTK+ 3)"
"Gtk3 lets Perl applications use the GTK+ 3"
"graphical user interface toolkit."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN1DIR=/usr/man/man1 \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
