#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Santiago Torres-Arias <santiago @ usualplace>
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python3-hatchling
_srcdir=hatch-hatchling-v1.27.0
pkgver=1.27.0
pkgrel=2slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Hatch build backend)"
""
"This is the extensible, standards-compliant build backend used by"
"Hatch."
""
"Homepage: https://github.com/pypa/hatch/tree/master/backend"
)
url="https://github.com/pypa/hatch/tree/master/backend"
license=("MIT")
depends=(
  "python3-editables"
  "python3-packaging"
  "python3-pathspec"
  "python3-pluggy"
  "python3-trove-classifiers"
)
makedepends=("python3-build" "python3-installer")
source=("https://github.com/pypa/hatch/archive/refs/tags/hatchling-v${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcdir}" || return 1
  python3 -m build --wheel --no-isolation backend || return 1
  python3 -m installer --destdir="$PKG" backend/dist/*.whl || return 1

  install -Dm 0644 LICENSE.txt "$PKG/usr/doc/$pkgname-$pkgver/LICENSE.txt" || return 1
  install -Dm 0644 README.md "$PKG/usr/doc/$pkgname-$pkgver/README.md" || return 1
}
