#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=OpenAL
srcname=openal-soft
export srcname
pkgver=1.21.1
pkgrel=1slint
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"OpenAL (a cross-platform 3D audio API)"
"OpenAL is a cross-platform 3D audio API appropriate for use with"
"gaming applications and many other types of audio applications."
)
url="https://www.openal-soft.org/"
license=("custom")
source=("https://www.openal-soft.org/openal-releases/openal-soft-${pkgver}.tar.bz2")
docs=("COPYING")

build() {
  cmake -B build -S "${srcname}-${pkgver}" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DALSOFT_EXAMPLES=OFF \
    -DLIB_SUFFIX="${LIBDIRSUFFIX}" \
    -Wno-dev || return 1

  cmake --build build -j "$numjobs" || return 1
  DESTDIR="$PKG" cmake --build build --target install/strip || return 1
}
