#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=snappy
pkgver=1.1.8
pkgrel=2slint
source=(
  "https://github.com/google/snappy/archive/${pkgver}/${pkgname}-${pkgver}.tar.gz"
  "73.patch"
)
docs=("README.md")
url="https://github.com/google/snappy"
options=("nosrcpack")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"snappy (a fast compressor/decompressor)"
""
"Snappy is a compression/decompression library."
"It does not aim for maximum compression or compatibility with other"
"compression libraries; instead, it aims for very high speeds and"
"reasonable compression."
)

build() {
  local legacyScriptName

  legacyScriptName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  patch -p1 < "$SRC/../73.patch" || return 1

  cmake -S . -B build \
    -DCMAKE_C_FLAGS="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS="$SLKCFLAGS" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS=ON || return 1

  cmake --build build || return 1
  DESTDIR="$PKG" cmake --install build || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyScriptName" || return 1
  find "$PKG/usr/doc/$pkgname-$pkgver" -type f -exec chmod 644 {} + || return 1
}
