#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-parallel-forkmanager
pkgver=2.02
pkgrel=1slint
depends=("perl-test-warn" "perl-Role-Tiny")
export srcname=perl-parallel-forkmanager
source=("https://github.com/dluxhu/perl-parallel-forkmanager/archive/v$pkgver/$srcname-$pkgver.tar.gz")
docs=("Changes" "CODE_OF_CONDUCT.md" "CONTRIBUTORS" "INSTALL" "README.mkdn")
url="https://github.com/dluxhu/perl-parallel-forkmanager"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-parallel-forkmanager (simple bounded parallel fork manager)"
"Runs many jobs in parallel while limiting child process count."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN1DIR=/usr/man/man1 \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
