#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python3-tqdm
srcname=tqdm
pkgver=4.63.0
pkgrel=1slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (fast, extensible progress meter for Python)"
""
"tqdm adds configurable progress bars to Python loops and"
"iterators with minimal overhead."
""
"Homepage: https://github.com/tqdm/tqdm"
)
url="https://github.com/tqdm/tqdm"
depends=("python3")
makedepends=("python3-setuptools")
source=("https://files.pythonhosted.org/packages/source/t/${srcname}/${srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  install -m 0644 LICENCE "$docdir/LICENCE" || return 1
  install -m 0644 PKG-INFO "$docdir/PKG-INFO" || return 1
  install -m 0644 README.rst "$docdir/README.rst" || return 1
}
