#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

pkgname=gst-plugins-good
pkgver=1.28.1
pkgrel=2slint
url="https://gstreamer.freedesktop.org/"
license=("LGPL-2.1-or-later")
source=("https://gstreamer.freedesktop.org/src/gst-plugins-good/${pkgname}-${pkgver}.tar.xz")
options=("nosrcpack")
docs=("AUTHORS*" "COPYING*" "NEWS*" "README*" "RELEASE*")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"gst-plugins-good (good set of GStreamer plugins)"
""
"GStreamer Good Plug-ins are a set of high-quality plug-ins."
"They provide correct functionality, broad usefulness, and"
"licensing suitable for general distribution."
)

build() {
  local docsDir

  docsDir="$PKG/usr/doc/$pkgname-$pkgver"

  cd "$SRC/$pkgname-$pkgver" || return 1

  meson setup buildDir \
    --prefix=/usr \
    --libdir="lib${LIBDIRSUFFIX}" \
    --libexecdir=/usr/libexec \
    --bindir=/usr/bin \
    --sbindir=/usr/sbin \
    --includedir=/usr/include \
    --datadir=/usr/share \
    --mandir=/usr/man \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Ddoc=disabled \
    -Dexamples=disabled \
    -Dtests=disabled || return 1

  meson compile -C buildDir -j "$numjobs" || return 1
  DESTDIR="$PKG" meson install -C buildDir || return 1

  install -Dm0644 "$SRC/../SLKBUILD" "$docsDir/SLKBUILD" || return 1
}
