#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Dimitris Zlatanidis <d.zlatanidis@gmail.com>
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python3-click
_srcname=click
pkgver=8.1.8
pkgrel=2slint
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Python 3 composable command line utility)"
""
"Click is a Python package for creating beautiful command line"
"interfaces in a composable way with as little code as necessary."
"It is highly configurable but comes with sensible defaults."
""
"Homepage: https://github.com/mitsuhiko/click"
)
url="https://pypi.org/project/click/"
license=("BSD")
depends=("python3")
makedepends=("python3-build" "python3-installer" "python3-wheel")
source=("https://files.pythonhosted.org/packages/source/c/click/click-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  python3 -m build --wheel --no-isolation || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  legacy_suffix=SlackBuild
  mkdir -p "$docdir"
  cp -a CHANGES.rst LICENSE.txt README.md docs/*.rst "$docdir"
  install -m 0644 "$SRC/../SLKBUILD" "$docdir/$pkgname.$legacy_suffix"
}
