#!/bin/bash
# shellcheck shell=bash disable=SC2034
pkgname=aerc
pkgver=0.14.0
pkgrel=3slint
options=("nosrcpack")
docs=("LICENSE" "README.md")
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (terminal email client)"
"URL: https://git.sr.ht/~rjarry/aerc"
)

source=("https://git.sr.ht/~rjarry/$pkgname/archive/$pkgver.tar.gz")

build() {
	cd "$SRC/${pkgname}-${pkgver}" || return 1
    export GOFLAGS="-tags=notmuch"
    make PREFIX=/usr
    make PREFIX=/usr DESTDIR="$PKG" install
}
