#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python-toml
_srcname=toml
pkgver=0.10.2
pkgrel=2slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (TOML parser and emitter for Python)"
""
"toml provides Python support for reading, writing, and"
"round-tripping TOML configuration files."
""
"Homepage: https://github.com/uiri/toml"
)
url="https://github.com/uiri/toml"
depends=("python")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/t/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  install -m 0644 LICENSE "$docdir/LICENSE" || return 1
  install -m 0644 README.rst "$docdir/README.rst" || return 1
}
