#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=pangomm48
_srcname=pangomm
pkgver=2.50.0
pkgrel=1slint
depends=('cairomm16' 'pango')
url="https://www.gtkmm.org/"
source=("https://download.gnome.org/sources/${_srcname}/${pkgver%.*}/${_srcname}-${pkgver}.tar.xz")
options=("nosrcpack")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"pangomm48 (C++ bindings for Pango 2.48 API)"
""
"pangomm48 provides the pangomm 2.48 API line so it can coexist"
"with the older pangomm package already shipped in Slint."
""
"Homepage: https://www.gtkmm.org/"
)

build() {
  local docdir

  docdir="$PKG/usr/doc/$pkgname-$pkgver"

  cd "$SRC/${_srcname}-${pkgver}" || return 1
  rm -rf meson-build || return 1

  meson setup meson-build . \
    --prefix=/usr \
    --libdir="lib${LIBDIRSUFFIX}" \
    --libexecdir=/usr/libexec \
    --bindir=/usr/bin \
    --sbindir=/usr/sbin \
    --includedir=/usr/include \
    --datadir=/usr/share \
    --mandir=/usr/man \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Dbuild-documentation=true \
    --wrap-mode=nofallback || return 1
  "${NINJA:=ninja}" -C meson-build -j "$numjobs" || return 1
  DESTDIR="$PKG" "$NINJA" -C meson-build install || return 1

  install -d "$docdir" || return 1
  cp -a AUTHORS COPYING* NEWS README* "$docdir/" || return 1
  if [ -r ChangeLog ]; then
    head -n 1000 ChangeLog > "$docdir/ChangeLog" || return 1
    touch -r ChangeLog "$docdir/ChangeLog" || return 1
  fi
}
