#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Benjamin Trigona-Harany <slackbuilds@jaxartes.net>
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python3-importlib-metadata
_srcname=importlib_metadata
pkgver=4.8.2
pkgrel=1slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Python package metadata access library)"
""
"importlib_metadata provides access to installed package"
"metadata such as entry points and top-level names."
""
"Homepage: https://importlib-metadata.readthedocs.io/"
)
url="https://importlib-metadata.readthedocs.io/"
license=("Apache-2.0")
depends=("python3" "python-zipp")
makedepends=("python3-setuptools")
source=("https://files.pythonhosted.org/packages/source/i/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1
  python3 setup.py install --root="$PKG" || return 1

  while IFS= read -r -d '' egginfo; do
    fixed_egginfo="${egginfo/${pkgver}/0.0.0}"
    mv "$egginfo" "$fixed_egginfo" || return 1
    sed -i 's/^Version: .*/Version: 0.0.0/' \
      "$fixed_egginfo/PKG-INFO" || return 1
  done < <(find "$PKG"/usr/lib* -type d -name "${_srcname}-${pkgver}-py*.egg-info" -print0)

  install -Dm 0644 README.rst "$PKG/usr/doc/$pkgname-$pkgver/README.rst" || return 1
}
