#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-JSON-XS
pkgver=4.03
pkgrel=1slint
export srcname=JSON-XS
source=("https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/$srcname-$pkgver.tar.gz")
docs=("COPYING" "README*" "Changes")
url="https://metacpan.org/pod/JSON::XS"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-JSON-XS (fast JSON serialization)"
"JSON::XS converts Perl data structures to"
"and from JSON with a C implementation."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  export PERL_MM_USE_DEFAULT=1
  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN1DIR=/usr/man/man1 \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
