#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libmodplug
pkgver=0.8.9.0
pkgrel=2slint
url="https://modplug-xmms.sourceforge.net/"
source=(
  "https://downloads.sourceforge.net/modplug-xmms/${pkgname}-${pkgver}.tar.gz"
  "libmodplug-0.8.4-timiditypaths.patch"
)
docs=("AUTHORS" "ChangeLog" "COPYING" "NEWS" "README" "TODO")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"libmodplug (mod rendering library)"
""
"libmodplug is a library based on the module rendering"
"code from ModPlug, a popular Windows module player."
""
"Homepage: https://modplug-xmms.sourceforge.net/"
)

build() {
  local changeLogName
  local legacyDocName

  changeLogName="ChangeLog"
  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  sed -e 's/\r//' "$changeLogName" > "${changeLogName}.new" || return 1
  touch -r "$changeLogName" "${changeLogName}.new" || return 1
  mv "${changeLogName}.new" "$changeLogName" || return 1

  patch -p1 --verbose < "$SRC/libmodplug-0.8.4-timiditypaths.patch" || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/man \
    --docdir="/usr/doc/$pkgname-$pkgver" \
    --disable-silent-rules \
    --build="$ARCH-slackware-linux" || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  find "$PKG"/usr/lib* -maxdepth 1 -name '*.la' -delete || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
