#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python-pylast
_srcname=pylast
pkgver=5.0.0
pkgrel=1slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Python interface to the Last.fm API)"
""
"pylast is a Python library for talking to Last.fm and"
"compatible web services."
""
"Homepage: https://github.com/pylast/pylast"
)
url="https://github.com/pylast/pylast"
depends=("python")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/p/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  install -m 0644 COPYING "$docdir/COPYING" || return 1
  install -m 0644 PKG-INFO "$docdir/PKG-INFO" || return 1
}
