= Speech-friendly Alsa Mixer (sam)

Controlling Alsa using a console terminal only is somewhat cumbersome.
The interactive tools is not speech-friendly, so I tried my hand at writing
a mixer which works well with  a screen reader, Speakup in my case.

== Features
* Allow selection of the sound card to work on when there are more than one
such device in your machine.
When there is only one, it directly presents the different mixers
for configuration.
+
All selections, be it sound cards, mixers or a given feature of a
 specific mixer are selected by scrolling through the available options using the up and down arrows, then entering on the desired one: +
`q` leave the selection list and/or quits. +
`Shift-q` exits the program from anywhere. +
`F1` Displays any extra information if available.
+
When the name of the desired option is known, one can instead press its
first letter. First-letter navigation is case-insensitive.
That will then take you to the first selection starting with the pressed
letter.  Pressing the same letter again, will move you to the next option
starting with that letter ifmore than one option like that exists.
Repeating the letter will cycle among all those options starting with that
letter.
* The settable features of a mixer can be  listed by pressing f1.
They are presented as a selection list, showing briefly all relevant information, e.g.
"playback volume down from 84 percent" is the option to lower the playback volume
setting of the playback volume.  As you can see, it also tells you what the
current setting is.

== Limitations
Alsa allows the different channels of a mixer to be set individually.
Sam always set them together. So you cannot set the left channel to 20
percent and the right one to 50 percent using Sam.

== Requirements
Note, the program will not work correctly from a terminal under X-windows.
It only works in a true console, Usually set up as tty1 through tty6 on most
machines.

== Running sam
From the dollar prompt, just type sam and enter.
You do need to have permissions to control your sound devices from your
user.

== Copyright
(C) 2019 Willem van der Walt <wvdwalt@csir.co.za>
Sam is released under the GNU license version 3 or later.
See the file COPYING for details.


