#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=libdvbpsi
pkgver=1.3.3
pkgrel=1slint
url="https://www.videolan.org/developers/libdvbpsi.html"
source=("https://download.videolan.org/pub/${pkgname}/${pkgver}/${pkgname}-${pkgver}.tar.bz2")
docs=("AUTHORS" "COPYING" "ChangeLog" "INSTALL" "NEWS" "README")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"libdvbpsi (library for MPEG TS and DVB PSI tables)"
""
"libdvbpsi is a library for decoding and generating"
"MPEG TS and DVB PSI tables."
""
"Homepage: https://www.videolan.org/developers/libdvbpsi.html"
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --docdir="/usr/doc/$pkgname-$pkgver" \
    --disable-static \
    --build="$ARCH-slackware-linux" || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG"/usr/lib*/*.la || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
