#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-PAR-Dist
pkgver=0.53
pkgrel=1slint
arch=noarch
export srcname=PAR-Dist
source=("https://cpan.metacpan.org/authors/id/R/RS/RSCHUPP/$srcname-$pkgver.tar.gz")
docs=("README*" "Changes")
url="https://metacpan.org/pod/PAR::Dist"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-PAR-Dist (create PAR distributions)"
"PAR::Dist creates and manipulates architecture-"
"specific PAR distributions from CPAN builds."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
