#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-IO-HTML
pkgver=1.004
pkgrel=1slint
export srcname=IO-HTML
source=("https://cpan.metacpan.org/authors/id/C/CJ/CJM/$srcname-$pkgver.tar.gz")
docs=("Changes" "LICENSE" "README")
url="https://metacpan.org/pod/IO::HTML"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-IO-HTML (open HTML files with charset detection)"
"IO::HTML opens HTML files while automatically"
"determining their character encoding."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
