#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-common-sense
pkgver=3.75
pkgrel=1slint
export srcname=common-sense
source=("https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/$srcname-$pkgver.tar.gz")
docs=("Changes" "LICENSE" "README")
url="https://metacpan.org/pod/common::sense"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-common-sense (common Perl defaults with low memory overhead)"
"Applies practical defaults and sanity tweaks for Perl programs."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
