#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libstatgrab
pkgver=0.92.1
pkgrel=2slint
url="https://www.i-scream.org/libstatgrab/"
source=("https://ftp.i-scream.org/pub/i-scream/libstatgrab/${pkgname}-${pkgver}.tar.gz")
docs=("AUTHORS" "COPYING*" "ChangeLog" "NEWS" "PLATFORMS" "README")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"libstatgrab (system statistics library)"
""
"libstatgrab is a C library that provides cross-platform"
"access to system statistics, including CPU usage,"
"memory utilization, disk usage, process counts,"
"network traffic, disk I/O, and more."
""
"Homepage: https://www.i-scream.org/libstatgrab/"
)

build() {
  local legacy_doc

  legacy_doc="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/man \
    --docdir="/usr/doc/$pkgname-$pkgver" \
    --disable-static \
    --build="$ARCH-slackware-linux" || return 1

  env MAKEFLAGS= make -j1 || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG"/usr/lib"${LIBDIRSUFFIX}"/*.la || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacy_doc" || return 1
}
