#!/bin/bash
# shellcheck shell=bash disable=SC2034
#Packager: Richard Lapointe <richard@laprjns.com>
#Modified for Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python3-lxml
export srcname=lxml
pkgver=6.0.2
pkgrel=1slint
source=("https://files.pythonhosted.org/packages/source/l/${srcname}/${srcname}-${pkgver}.tar.gz")
sourcetemplate=http://people.salixos.org/laprjns/$pkgname/$pkgver/
depends=("libxml2" "libxslt" "python3")
makedepends=("python3-build" "python3-installer" "python3-setuptools" "python3-wheel")
options=('nosrcpack')

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"lxml (Python bindings for libxml2 and libxslt)"
"lxml is a Pythonic binding for the libxml2 and libxslt libraries. It"
"is unique in that it combines the speed and feature completeness of"
"these libraries with the simplicity of a native Python API,"
"mostly compatible but superior to the well-known ElementTree API."
)

build() {
	local docDir
	local docFile

	docDir="$PKG/usr/doc/$pkgname-$pkgver"
	cd "${srcname}-${pkgver}" || return 1
	python3 -m build --wheel --no-isolation || return 1
	python3 -m installer --destdir="$PKG" dist/*.whl || return 1

	install -d "$docDir" || return 1
	for docFile in CHANGES.txt CREDITS.txt LICENSE.txt LICENSES.txt README.rst TODO.txt doc/licenses/BSD.txt doc/licenses/GPL.txt doc/licenses/elementtree.txt; do
		[[ -e "$docFile" ]] || continue
		cp -a "$docFile" "$docDir/" || return 1
	done
}
