#!/bin/bash
# shellcheck shell=bash disable=SC2034
#Packager: Richard Lapointe <richard@laprjns.com>
#Modified for Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python3-lxml
export srcname=lxml
pkgver=4.9.4
pkgrel=1slint
source=("https://files.pythonhosted.org/packages/source/l/${srcname}/${srcname}-${pkgver}.tar.gz")
sourcetemplate=http://people.salixos.org/laprjns/$pkgname/$pkgver/
options=('nosrcpack')

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"lxml (Python bindings for libxml2 and libxslt)"
"lxml is a Pythonic binding for the libxml2 and libxslt libraries. It"
"is unique in that it combines the speed and feature completeness of"
"these libraries with the simplicity of a native Python API,"
"mostly compatible but superior to the well-known ElementTree API."
)

build() {
	local docDir
	local docFile
	local sourceDir

	docDir="$PKG/usr/doc/$pkgname-$pkgver"
	sourceDir="$(find . "$SRC" -maxdepth 2 -type d -name "${srcname}-${pkgver}" 2>/dev/null | head -n 1)"
	if [[ -z "$sourceDir" ]]; then
		return 1
	fi

	cd "$sourceDir" || return 1
	python3 setup.py build --with-unicode-strings --without-cython || return 1
	python3 setup.py install --prefix=/usr --root="$PKG" --skip-build --optimize=1 || return 1

	install -d "$docDir" || return 1
	for docFile in CREDITS.txt LICENSE.txt LICENSES.txt README.rst TODO.txt BSD.txt GPL.txt ZopePublicLicense.txt elementtree.txt; do
		[[ -e "$docFile" ]] || continue
		cp -a "$docFile" "$docDir/" || return 1
	done
}
