#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libplacebo
pkgver=6.338.2
pkgrel=2slint
gladver=2.0.8
jinjaver=3.1.6
markupsafever=3.0.3
url="https://code.videolan.org/videolan/libplacebo"
license=("LGPL-2.1-or-later")
source=(
  "https://github.com/haasn/libplacebo/archive/refs/tags/v${pkgver}.tar.gz"
  "libplacebo-silence-git-describe.patch"
  "https://files.pythonhosted.org/packages/source/g/glad2/glad2-${gladver}.tar.gz"
  "https://github.com/pallets/jinja/archive/refs/tags/${jinjaver}.tar.gz"
  "https://github.com/pallets/markupsafe/archive/refs/tags/${markupsafever}.tar.gz"
)
options=("nosrcpack")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"libplacebo (GPU-accelerated video processing library)"
""
"libplacebo is, in a nutshell, the core rendering algorithms and ideas"
"of mpv rewritten as an independent library. It contains a large"
"assortment of video processing shaders, focusing on both quality and"
"performance."
)

build() {
  local docsDir
  local docPath
  local gladver=2.0.8
  local jinjaver=3.1.6
  local markupsafever=3.0.3
  local glslangArg="-Dglslang=disabled"

  cd "$SRC/$pkgname-$pkgver" || return 1

  patch -p1 < "$SRC/libplacebo-silence-git-describe.patch" || return 1
  rm -rf 3rdparty/glad 3rdparty/jinja 3rdparty/markupsafe || return 1
  mkdir -p 3rdparty || return 1
  cp -a "$SRC/glad2-$gladver" 3rdparty/glad || return 1
  cp -a "$SRC/jinja-$jinjaver" 3rdparty/jinja || return 1
  cp -a "$SRC/markupsafe-$markupsafever" 3rdparty/markupsafe || return 1

  if pkg-config --exists glslang; then
    glslangArg="-Dglslang=enabled"
  fi

  meson setup meson-build \
    --prefix=/usr \
    --libdir="lib${LIBDIRSUFFIX}" \
    --libexecdir=/usr/libexec \
    --bindir=/usr/bin \
    --sbindir=/usr/sbin \
    --includedir=/usr/include \
    --datadir=/usr/share \
    --mandir=/usr/man \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Ddemos=false \
    "$glslangArg" \
    -Ddovi=disabled \
    -Dlibdovi=disabled \
    -Dd3d11=disabled || return 1

  ninja -j "$numjobs" -C meson-build || return 1
  DESTDIR="$PKG" ninja -C meson-build install || return 1

  docsDir="$PKG/usr/doc/$pkgname-$pkgver"
  mkdir -p "$docsDir" || return 1
  for docPath in LICENSE* README*; do
    [ -e "$docPath" ] || continue
    cp -a "$docPath" "$docsDir" || return 1
  done
}
