#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-Mozilla-CA
pkgver=20211001
pkgrel=1slint
export srcname=Mozilla-CA
source=("https://cpan.metacpan.org/authors/id/A/AB/ABH/$srcname-$pkgver.tar.gz")
docs=("Changes" "README")
url="https://metacpan.org/pod/Mozilla::CA"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-Mozilla-CA (Mozilla CA cert bundle in PEM format)"
"Mozilla::CA provides Mozilla's CA certificate bundle in"
"PEM format."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
