#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-CDDB-get
pkgver=2.28.1
pkgrel=2slint
export srcname=CDDB_get
source=("https://backpan.perl.org/modules/by-authors/id/F/FO/FONKIE/$srcname-$pkgver.tar.gz")
docs=("Artistic" "Changes" "Copying" "README")
url="https://metacpan.org/pod/CDDB_get"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-CDDB-get (read CDDB entries for audio CDs)"
"CDDB_get retrieves metadata for audio discs from"
"CDDB services."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
