#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libmateweather
pkgver=1.28.0
pkgrel=1slint
url="https://www.mate-desktop.org/"
source=("https://pub.mate-desktop.org/releases/1.28/${pkgname}-${pkgver}.tar.xz")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"libmateweather (weather library for the MATE desktop)"
""
"libmateweather provides access to online weather data for"
"numerous locations for the MATE desktop."
""
"Homepage: https://www.mate-desktop.org/"
)

doinst() {
cat <<'EOF'
if [ -x /usr/bin/update-desktop-database ]; then
  /usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
  /usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
  if [ -x /usr/bin/gtk-update-icon-cache ]; then
    /usr/bin/gtk-update-icon-cache -f usr/share/icons/hicolor >/dev/null 2>&1
  fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
  if [ -x /usr/bin/glib-compile-schemas ]; then
    /usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
  fi
fi
EOF
}

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/man \
    --docdir="/usr/doc/$pkgname-$pkgver" \
    --disable-static \
    --enable-locations-compression \
    --build="$ARCH-slackware-linux" || return 1

  make -j"$numjobs" || make || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG"/{,usr/}lib"${LIBDIRSUFFIX}"/*.la || return 1

  mkdir -p "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  cp -a AUTHORS COPYING ChangeLog INSTALL NEWS README \
    "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
