#!/bin/bash

# Slackware build script for zd1211-firmware

# Packager: Didier Spaier didieratslintdotfr

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=zd1211-firmware
VERSION=${VERSION:-1.5}
BUILD=${BUILD:-1}
TAG=${TAG:-slint}
PKGTYPE=${PKGTYPE:-txz}

if [ -z "$ARCH" ]; then
  ARCH=fw
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-$CWD}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-$CWD}

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM
tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
cd $PRGNAM

chown -R root:root .
chmod 644 ./*

mkdir -p $PKG/lib/firmware/zd1211
cp -a ./* $PKG/lib/firmware/zd1211

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
ln -s ../../../lib/firmware/zd1211/COPYING $PKG/usr/doc/$PRGNAM-$VERSION/COPYING
ln -s ../../../lib/firmware/zd1211/README $PKG/usr/doc/$PRGNAM-$VERSION/README
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
