#!/bin/bash
# shellcheck shell=bash disable=SC2034

pkgname=python-gast
pkgver=0.6.0
pkgrel=1slint
slackdesc="$pkgname (AST that abstracts the underlying Python version)"
url="https://github.com/serge-sans-paille/gast"
license=('BSD')
depends=('python3')
makedepends=('python3-setuptools')
source=("https://files.pythonhosted.org/packages/source/g/gast/gast-${pkgver}.tar.gz")
sha256sums=('88fc5300d32c7ac6ca7b515310862f71e6fdf2c029bbec7c66c0f5dd47b6b1fb')
docs=(LICENSE README.rst)
build() {
  cd "gast-${pkgver}" || return 1
  python3 setup.py build || return 1
  python3 setup.py install --root="$PKG" --optimize=1 --skip-build || return 1
}
