diff -ru mujs-1.3.3/Makefile mujs-1.3.3.new/Makefile
--- mujs-1.3.3/Makefile	2023-01-10 12:11:11.000000000 +0100
+++ mujs-1.3.3.new/Makefile	2023-10-23 22:20:31.155473650 +0200
@@ -8,10 +8,10 @@
 
 OPTIM = -O3
 
-prefix = /usr/local
+prefix = /usr
 bindir = $(prefix)/bin
 incdir = $(prefix)/include
-libdir = $(prefix)/lib
+libdir = $(prefix)/lib64
 
 ifeq ($(wildcard .git),.git)
   VERSION = $(shell git describe --tags --always)
