#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Maintainer: Jan Alexander Steffens (heftig) <heftig@archlinux.org>
# Contributor: Jan de Groot <jgc@archlinux.org>
# Contributor: Ionut Biru <ibiru@archlinux.org>
# Contributor: uastasi <uastasi@archlinux.us>
# Included in Slint by Didier Spaier didieratslintdotfr
pkgname=gnote
pkgver=44.2
pkgrel=3slint
slackdesc=("$pkgname (Gnote is a simple note-taking application.)"
"Gnote is a simple note-taking application."
"It allows you to capture your ideas, link them together using"
"WikiWiki style links")
url="https://wiki.gnome.org/Apps/Gnote"
source=("https://download.gnome.org/sources/${pkgname}/${pkgver%.*}/${pkgname}-${pkgver}.tar.xz")
arch=(x86_64)
license=(GPL-3.0-or-later)
depends=(
  dconf
  gcc-libs
  glib2
  glibc
  glibmm
  gspell
  gtkmm3
  hicolor-icon-theme
  libsecret
  libxml2
  libxslt
  util-linux
)
makedepends=(
  git
  meson
  yelp-tools
)
doinst() {
# Update any existing icon cache files:
if find /usr/share/icons -maxdepth 2 2> /dev/null | grep -q icon-theme.cache ; then
  for theme_dir in /usr/share/icons/* ; do
    if [ -r "${theme_dir}/icon-theme.cache" ]; then
      /usr/bin/gtk-update-icon-cache -t -f "${theme_dir}" 1> /dev/null 2> /dev/null &
    fi
  done
  # This would be a large file and probably shouldn't be there.
  if [ -r /usr/share/icons/icon-theme.cache ]; then
    rm -f /usr/share/icons/icon-theme.cache
  fi
fi
# Update desktop database:
if [ -x /usr/bin/update-desktop-database ]; then
  /usr/bin/update-desktop-database /usr/share/applications 1> /dev/null 2> /dev/null
fi
}
build() {
cd "${pkgname}-${pkgver}" || return 1
mkdir build
  CFLAGS="$SLKCFLAGS" \
  CXXFLAGS="$SLKCFLAGS" \
  meson setup \
    --buildtype=release \
    --infodir=/usr/info \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --localstatedir=/var \
    --prefix=/usr \
    --sysconfdir=/etc \
   build
   meson compile -C build
   meson install -C build --destdir "$PKG"
cd .. || return 1
}

# vim:set sw=2 sts=-1 et:
