#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154
# Packager: sektor

pkgname=kbd
pkgver=2.6.3
pkgrel=1slint
source=(
  "https://mirrors.edge.kernel.org/pub/linux/utils/kbd/kbd-${pkgver}.tar.xz"
  "fix-euro2.patch"
  "kbd-1.15-backspace-1.patch.gz"
  "extraf.tgz"
  "setconsolefont"
  "setup.setconsolefont"
  "vlock.pam"
)
dotnew=(
  "etc/pam.d/vlock"
  "etc/rc.d/rc.font"
)
url="https://kbd-project.org/"

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"kbd (keyboard maps and console fonts)"
""
"Load and save keyboard mappings. Needed if you are not using the US"
"keyboard map. This package also contains utilities to change your"
"console fonts - if you install it you'll get a menu later on that lets"
"you select from many different fonts. If you like one, you can make"
"it your default font. A new default font can be chosen at any time by"
"typing 'setconsolefont'."
""
""
""
""
)

doinst() {
  if [ -e etc/rc.d/rc.font ] && [ -e etc/rc.d/rc.font.new ]; then
    if [ -x etc/rc.d/rc.font ]; then
      chmod 755 etc/rc.d/rc.font.new
    else
      chmod 644 etc/rc.d/rc.font.new
    fi
  fi
}

build() {
  local helperdir

  cd "${pkgname}-${pkgver}" || return 1
  helperdir="$(cd .. && pwd)" || return 1

  zcat ../kbd-1.15-backspace-1.patch.gz | patch -p1 --verbose || return 1
  patch -Np1 -i ../fix-euro2.patch || return 1

  sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure || return 1
  sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in || return 1

  cp -fav data/keymaps/i386/qwerty/pt-latin9.map data/keymaps/i386/qwerty/pt.map || return 1
  cp -fav data/keymaps/i386/qwerty/sv-latin1.map data/keymaps/i386/qwerty/se-latin1.map || return 1
  mv -fv data/keymaps/i386/azerty/fr.map data/keymaps/i386/azerty/fr-old.map || return 1
  cp -fav data/keymaps/i386/azerty/fr-latin9.map data/keymaps/i386/azerty/fr.map || return 1
  cp -fav data/keymaps/i386/azerty/fr-latin9.map data/keymaps/i386/azerty/fr-latin0.map || return 1

  mv data/keymaps/i386/colemak/en-latin9.map data/keymaps/i386/colemak/colemak.map || return 1
  mv data/keymaps/i386/fgGIod/trf.map data/keymaps/i386/fgGIod/trf-fgGIod.map || return 1
  mv data/keymaps/i386/olpc/es.map data/keymaps/i386/olpc/es-olpc.map || return 1
  mv data/keymaps/i386/olpc/pt.map data/keymaps/i386/olpc/pt-olpc.map || return 1
  mv data/keymaps/i386/qwerty/cz.map data/keymaps/i386/qwerty/cz-qwerty.map || return 1

  ./configure \
    --prefix=/usr \
    --libdir=/usr/lib"${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --datadir=/usr/share/kbd \
    --mandir=/usr/man \
    --docdir=/usr/doc/${pkgname}-${pkgver} \
    --localedir=/usr/share/locale/ \
    --enable-nls \
    --enable-optional-progs \
    --enable-libkeymap \
    --disable-tests \
    --disable-static || return 1

  make -j"$numjobs" || make || return 1
  make DESTDIR="$PKG" install || return 1

  rm -f "$PKG/usr/share/kbd/keymaps/i386/qwerty/ro_win.map.gz" || return 1
  install -Dm0644 ../vlock.pam "$PKG/etc/pam.d/vlock" || return 1

  (
    cd "$PKG" || exit 1
    explodepkg "${helperdir}/extraf.tgz"
  ) || return 1

  if [ ! -r "$PKG/usr/man/man1/kbdinfo.1" ]; then
    install -Dm0644 docs/man/man1/kbdinfo.1 "$PKG/usr/man/man1/kbdinfo.1" || return 1
  fi

  install -Dm0755 ../setup.setconsolefont "$PKG/var/log/setup/setup.setconsolefont" || return 1
  install -Dm0755 ../setconsolefont "$PKG/usr/bin/setconsolefont" || return 1

  install -d "$PKG/etc/rc.d" || return 1
  cat > "$PKG/etc/rc.d/rc.font" <<'EOF' || return 1
#!/bin/sh
#
# This selects your default screen font from among the ones in
# /usr/share/kbd/consolefonts.
#
setfont -v
EOF
  chmod 0644 "$PKG/etc/rc.d/rc.font" || return 1

  rm -f "$PKG"/lib"${LIBDIRSUFFIX}"/*.la "$PKG"/usr/lib"${LIBDIRSUFFIX}"/*.la || return 1

  install -d "$PKG/usr/doc/${pkgname}-${pkgver}" || return 1
  cp -a AUTHORS COPYING CREDITS NEWS README "$PKG/usr/doc/${pkgname}-${pkgver}" || return 1
  if [ -r ChangeLog ]; then
    head -n 1000 ChangeLog > "$PKG/usr/doc/${pkgname}-${pkgver}/ChangeLog" || return 1
    touch -r ChangeLog "$PKG/usr/doc/${pkgname}-${pkgver}/ChangeLog" || return 1
  fi
}
