#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=potrace
pkgver=1.16
pkgrel=1slint
url="https://potrace.sourceforge.net/"
source=("https://potrace.sourceforge.net/download/${pkgver}/${pkgname}-${pkgver}.tar.gz")
docs=("AUTHORS" "COPYING" "ChangeLog" "INSTALL" "NEWS" "README")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"potrace (bitmap tracing utility)"
""
"Potrace traces bitmaps into smooth, scalable vector images."
"It accepts PBM, PGM, PPM, or BMP input and can produce"
"SVG, PDF, EPS, PostScript, DXF, GeoJSON, Gimppath,"
"XFig, and other output formats."
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/man \
    --infodir=/usr/info \
    --disable-dependency-tracking \
    --enable-shared \
    --disable-static \
    --with-libpotrace \
    --build="$ARCH-slackware-linux" || return 1

  make || return 1
  make check || return 1
  make install-strip DESTDIR="$PKG" || return 1

  find "$PKG/usr/lib${LIBDIRSUFFIX}" -name '*.la' -delete || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
