#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libdaemon
pkgver=0.14
pkgrel=2slint
url="https://0pointer.de/lennart/projects/libdaemon/"
source=("https://0pointer.de/lennart/projects/libdaemon/${pkgname}-${pkgver}.tar.gz")
docs=("LICENSE" "README")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"libdaemon (Unix daemonizing library)"
""
"libdaemon is a lightweight C library that eases the"
"writing of Unix daemons."
""
"Homepage: https://0pointer.de/lennart/projects/libdaemon/"
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --docdir="/usr/doc/$pkgname-$pkgver" \
    --disable-static \
    --build="$ARCH-slackware-linux" || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG"/usr/lib*/*.la || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
