#!/bin/sh
# shellcheck disable=SC1090

export PKGNAME=modules-installer
export ARCH=x86_64
export BUILD=1slint
CWD=$(pwd)
PKG=$CWD/pkg
rm -rf $PKG
mkdir $PKG
KERNELPKG=$(find ../../packages -name "kernel-[[:digit:]]*txz")
VERSION=$(printf "%b" "$KERNELPKG"|sed 's/.*-\([^-]*\)-[^-]*-[^-]*$/\1/')
( cd $PKG
tar xf ../$KERNELPKG lib/modules
mkdir install
echo "modules-installer: modules-installer (kernel modules for the installer)" > install/slack-desc
/sbin/makepkg -l y -c n "$CWD"/"$PKGNAME"-"$VERSION"-"$ARCH"-"$BUILD".txz
)
