Music Player Daemon (MPD) is a daemon for playing music of various
formats.  Music is played through the  server's audio device.  The
daemon stores info about all available music, and this info can be
easily searched and retrieved.  Player control, info retrieval, and
playlist management can all be managed remotely, or instance over a
local network. It also makes a great desktop music  player, especially
if you are a console junkie,like frontend options, or restart X often.

This package is built with patches providing SACD and DVDA ISO playback.

Be sure to edit the config file (/etc/mpd.conf  or ~/mpd.conf) before
running the daemon

Included documentation:
man mpd
man mpd.conf

Documents in HTML form are provided in
/usr/doc/mpd-sacd-0.23.11/
