#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=librsync
pkgver=2.3.4
pkgrel=1slint
url="https://librsync.github.io/"
source=("https://github.com/librsync/librsync/archive/v${pkgver}/${pkgname}-${pkgver}.tar.gz")
docs=("AUTHORS" "CONTRIBUTING.md" "COPYING" "NEWS.md" "README.md" "THANKS" "TODO.md")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (rsync synchronization algorithm library)"
"$pkgname is a free software library that implements the rsync"
"remote-delta algorithm."
"The rsync remote-delta algorithm efficiently transmits a structure"
"such as a file when the receiving computer already has a"
"different version of the same structure."
)

build() {
  rm -rf build || return 1

  cmake -B build -S "$SRC/$pkgname-$pkgver" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR="lib${LIBDIRSUFFIX}" \
    -DCMAKE_INSTALL_MANDIR=/usr/man || return 1

  cmake --build build -j "$numjobs" || return 1
  DESTDIR="$PKG" cmake --build build --target install || return 1
}
