#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint Python 3.11 migration

pkgname=python3-cython
export srcname=cython
pkgver=3.2.4
pkgrel=1slint
source=("https://files.pythonhosted.org/packages/91/85/7574c9cd44b69a27210444b6650f6477f56c75fee1b70d7672d3e4166167/${srcname}-${pkgver}.tar.gz")
url="https://cython.org/"
license=("Apache-2.0")
depends=("python3")
makedepends=("python3-build" "python3-installer" "python3-setuptools" "python3-wheel")
options=("nosrcpack")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"python3-cython (C extension compiler for Python 3)"
""
"Cython compiles Python-like code into C extension modules."
)

build() {
  local docDir
  local docFile

  docDir="$PKG/usr/doc/$pkgname-$pkgver"

  cd "${srcname}-${pkgver}" || return 1
  python3 -m build --wheel --no-isolation || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1

  if [[ ! -e "$PKG/usr/bin/cython3" && -e "$PKG/usr/bin/cython" ]]; then
    ln -sf cython "$PKG/usr/bin/cython3" || return 1
  fi
  if [[ ! -e "$PKG/usr/bin/cythonize3" && -e "$PKG/usr/bin/cythonize" ]]; then
    ln -sf cythonize "$PKG/usr/bin/cythonize3" || return 1
  fi
  if [[ ! -e "$PKG/usr/bin/cygdb3" && -e "$PKG/usr/bin/cygdb" ]]; then
    ln -sf cygdb "$PKG/usr/bin/cygdb3" || return 1
  fi

  install -d "$docDir" || return 1
  for docFile in CHANGES.rst COPYING.txt INSTALL.txt LICENSE.txt README.rst USAGE.txt; do
    [[ -e "$docFile" ]] || continue
    cp -a "$docFile" "$docDir/" || return 1
  done
}
