#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Antonio Rojas <arojas@archlinux.org>

#Included in Slint by Didier Spaier didieratslintdotfr
pkgname=yt-dlp-ejs
pkgver=0.5.0
pkgrel=5slint
export srcname=yt_dlp_ejs
slackdesc="$pkgname (External JavaScript for yt-dlp supporting many runtimes)"
url='https://github.com/yt-dlp/ejs'
license=(Unlicense)
depends=(deno
         python)
makedepends=(nodejs
             pnpm
             python3-build
             python-hatch-vcs
             python3-hatchling
             python3-installer)
checkdepends=(python-pytest)
source=("https://files.pythonhosted.org/packages/source/y/yt-dlp-ejs/${srcname}-${pkgver}.tar.gz")
sha256sums=('8dfae59e418232f485253dcf8e197fefa232423c3af7824fe19e4517b173293b')
docs=("LICENSE" "README.md")
build() {
  cd "$SRC/${srcname}-${pkgver}" || return 1
  sed -i '/3\.14/d' pyproject.toml
  sed -i '/3\.13/d' pyproject.toml
  python3 -m build --wheel --no-isolation
  python3 -m installer --destdir="$PKG" dist/*.whl
}
