#!/bin/sh
mkdir -p ~/.local/bin
scversion="stable"
rm -f ~/.local/bin/shellcheck
wget -qO- "https://github.com/koalaman/shellcheck/releases/download/${scversion?}/shellcheck-${scversion?}.linux.x86_64.tar.xz" | tar -xJv
cp "shellcheck-${scversion}/shellcheck" ~/.local/bin/
#~/.local/bin/shellcheck --version
export PATH=~/.local/bin/:$PATH

