speechd-el relies on brltty, emacs, and speech-dispatcher.

This directory contains information found in the speechd-el source
archive.

The subdirectory html/ contains information in HTML format that
you can read with a web browser. The start page is index.html

The subdirectory texi/ contains information files in TEX format.

An info page speechd-info is also stored in /usr/info.

Last but not least: to use emacspeak, add these lines at the top your
~/.emacs file:
(setq speechd-out-active-drivers '(ssip ))
(autoload 'speechd-speak
"speechd-speak" nil t)
(speechd-speak)

Emacs should then begin to speak as soon as you start it.

Alernatively, run as regular user this command:
switch-on speechd-el

This will disable emacspeak and include on top of ~/.emacs this line:
(autoload 'speechd-speak "speechd-speak" nil t)

You still have to append the other lines to ~/.emacs though.

Thanks to Peter Vágner for thhe information, cf.
https://pvagner.tk/2016/emacs-a11y-tip-1-introduction-and-how-to-install

I quote the Peter on how he sets the voice he uses:

-- quoted text begins below
For setting up the default voice you can alter the speechd-voices variable.
I don't know enough elisp syntaks to come up with proposed changes my-self,
however I have used M-x customize-group <ret> speechd <ret>
and customized my default voice to sk there.
This is what I've got...

speechd-voices
   (quote
    ((nil
      (name . "male1")
      (rate . 80)
      (pitch . 0)
      (volume . 100)
      (language . "sk"))))

This is the default voice and it applies to all content.
Content meaning all the textual data in the editor where you have no
language set (the default).
Default emacs prompts are most likelly coming from emacs localization thus
those strings already carry some information about its language. And
speechd-el is applying such a language voice when passing these strings to
speech-dispatcher for TTS.
Perhaps there is a way to override this somehow forcing the default voice
everywhere but I like it the way it's currently working thus I haven't
looked into it.

For changing voice and rate on the fly there are C-e d l and C-e d r key
bindings or for rate even C-e 1 (slowest) to C-e 9 (fastest) presets.
-- quoted text ended above

Didier Spaier
didier~at~slint~dot~fr
Last modified: 9 July 2021

