#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-Canary-Stability
pkgver=2013
pkgrel=1slint
export srcname=Canary-Stability
source=("https://cpan.metacpan.org/authors/id/M/ML/MLEHMANN/$srcname-$pkgver.tar.gz")
docs=("COPYING" "Changes" "README")
url="https://metacpan.org/release/Canary-Stability"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-Canary-Stability (Perl compatibility canary)"
"Canary::Stability checks Perl compatibility for"
"schmorp's modules."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN1DIR=/usr/man/man1 \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
