#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python-attrs
_srcname=attrs
pkgver=21.4.0
pkgrel=2slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (attributes without boilerplate)"
""
"attrs is an MIT-licensed Python package with class decorators"
"that ease the chores of implementing the most common"
"attribute-related object protocols."
""
"Homepage: https://pypi.org/project/attrs/"
)
url="https://pypi.org/project/attrs/"
depends=("python")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/a/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  for pybin in python3.9 python3.11; do
    "$pybin" setup.py install --root="$PKG" || return 1
  done

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  shopt -s nullglob
  for doc in LICENSE *.rst docs; do
    [[ -e $doc ]] || continue
    cp -a "$doc" "$docdir/" || return 1
  done
  shopt -u nullglob

  if [[ -d $docdir/docs ]]; then
    find "$docdir/docs" -type f -exec chmod 0644 {} + || return 1
  fi
}
