#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=gnustep-base
pkgver=1.31.1
pkgrel=2slint
url="https://www.gnustep.org/"
source=(
  "https://ftp.gnustep.org/pub/gnustep/core/${pkgname}-${pkgver}.tar.gz"
  "icu68.patch"
)

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"gnustep-base (GNUstep base library)"
""
"gnustep-base provides the general-purpose non-graphical"
"Objective-C classes used by the GNUstep environment."
""
"Homepage: https://www.gnustep.org/"
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  patch -p1 < "$SRC/../icu68.patch" || return 1

  ./configure \
    --prefix=/usr \
    --mandir=/usr/man \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --enable-ffcall \
    --build="$ARCH-slackware-linux" || return 1

  make -j"$numjobs" || make || return 1
  make install DESTDIR="$PKG" GNUSTEP_INSTALLATION_DOMAIN=SYSTEM || return 1

  chown -R root:root "$PKG/usr/lib${LIBDIRSUFFIX}/GNUstep/Libraries" || return 1
  chmod -R go-w "$PKG/usr/lib${LIBDIRSUFFIX}/GNUstep/Libraries" || return 1

  mkdir -p "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  cp -a ANNOUNCE COPYING COPYING.LIB COPYINGv3 ChangeLog NEWS README.md \
    "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
