#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libmp4v2
pkgver=20191108_9084868
pkgrel=3slint
url="https://github.com/sergiomb2/libmp4v2"
source=(
  "https://github.com/sergiomb2/libmp4v2/archive/9084868.tar.gz"
  "libmp4v2_gcc_narrowing.patch"
)

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"libmp4v2 (library to read, create, and modify MP4 files)"
""
"libmp4v2 provides functions to read, create, and modify"
"MP4 files in a standalone library derived from the"
"mpeg4ip source tree."
""
"Homepage: https://github.com/sergiomb2/libmp4v2"
)

build() {
  local docDir
  local _srcname
  local legacyDocName

  docDir="$PKG/usr/doc/$pkgname-$pkgver"
  _srcname="libmp4v2-9084868fd9f86bee118001c23171e832f15009f4"
  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/${_srcname}" || return 1

  patch --verbose -p1 < "$SRC/../libmp4v2_gcc_narrowing.patch" || return 1

  autoreconf -vif || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/man \
    --build="$ARCH-slackware-linux" || return 1

  make -j"$numjobs" || make || return 1
  make install DESTDIR="$PKG" || return 1

  mkdir -p "$docDir" || return 1
  cp -a COPYING README "$docDir" || return 1
  find "$docDir" -type f -exec chmod 0644 {} + || return 1
  rm -f "$PKG"/usr/lib*/*.la || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$docDir/$legacyDocName" || return 1
}
