#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Packager: Didier Spaier didieratslintdotfr

pkgname=python3-pluggy
pkgver=1.5.0
pkgrel=4slint
source=(
  "https://files.pythonhosted.org/packages/source/p/pluggy/pluggy-${pkgver}.tar.gz"
)
url="https://github.com/pytest-dev/pluggy"
options=('nosrcpack')

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"python3-pluggy: python3-pluggy (mechanisms for python)"
"python3-pluggy:"
"python3-pluggy: Plugin manager used by pytest, without pytest details."
"python3-pluggy:"
"python3-pluggy:"
"python3-pluggy: Homepage: https://github.com/pytest-dev/pluggy"
"python3-pluggy:"
"python3-pluggy:"
"python3-pluggy:"
"python3-pluggy:"
)

build() {
  cd "$SRC/pluggy-$pkgver" || exit 1

  python3 setup.py install --root="$PKG"

  mkdir -p "$PKG/usr/doc/$pkgname-$pkgver"
  cp -a CHANGELOG.rst LICENSE README.rst \
    "$PKG/usr/doc/$pkgname-$pkgver"
}
