#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python-imagesize
_srcname=imagesize
pkgver=1.3.0
pkgrel=1slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Python library to detect image dimensions)"
""
"imagesize reads common image formats and reports width"
"and height without fully decoding the image payload."
""
"Homepage: https://github.com/shibukawa/imagesize_py"
)
url="https://github.com/shibukawa/imagesize_py"
depends=("python")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/i/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  install -m 0644 README.rst "$docdir/README.rst" || return 1
}
