#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python-alabaster
_srcname=alabaster
pkgver=0.7.12
pkgrel=1slint
url="https://alabaster.readthedocs.io/"
depends=("python")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/a/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Sphinx theme)"
""
"Alabaster is a configurable Sphinx theme for Sphinx-based"
"documentation."
""
"Homepage: https://alabaster.readthedocs.io/"
)

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1
  cp -a LICENSE README.rst "$docdir/" || return 1
}
