#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Evangelos Foutras <evangelos@foutrelis.com>
# Contributor: Timm Preetz <timm@preetz.us>
# Included in  Slint by Didier Spaier diideratsintdotfr
pkgname=python3-pygments
pkgver=2.11.2
pkgrel=1slint
slackdesc="$pkgname (Python syntax highlighter)"
url="https://pygments.org/"
license=('BSD')
depends=('python3-setuptools')
makedepends=('python-sphinx' 'python-wcag-contrast-ratio')
checkdepends=('python-pytest' 'python-lxml')
provides=('pygmentize')
conflicts=('pygmentize')
replaces=('pygmentize')
source=(https://pypi.org/packages/source/P/Pygments/Pygments-$pkgver.tar.gz)
sha256sums=('4e426f72023d88d03b2fa258de560726ce890ff3b630f88c21cbb8b2503b8c6a')
docs=(LICENSE)

build() {
  cd "Pygments-$pkgver" || return 1
  make -C doc html || return 1
  python3 setup.py install --root="$PKG" -O1 || return 1
  install -Dm644 doc/pygmentize.1 -t "$PKG/usr/man/man1"
  mkdir -p "$PKG/usr/share/doc/$pkgname-$pkgver" || return 1
  cp -rT doc/_build/html "$PKG/usr/share/doc/$pkgname-$pkgver" || return 1
  install -Dm644 external/pygments.bashcomp \
    "$PKG/usr/share/bash-completion/completions/pygmentize"
}

# vim:set ts=2 sw=2 et:
