#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libcacard
pkgver=2.8.1
pkgrel=1slint
url="https://www.spice-space.org/"
source=("https://www.spice-space.org/download/libcacard/${pkgname}-${pkgver}.tar.xz")
docs=("COPYING" "ChangeLog" "NEWS" "README.md")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"libcacard (virtual smart card emulator library)"
""
"libcacard provides a virtual smart card emulator for guest"
"virtual machines and card readers, using either real smart"
"cards or software-defined card implementations."
""
"Homepage: https://www.spice-space.org"
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/man \
    --docdir="/usr/doc/$pkgname-$pkgver" \
    --disable-static \
    --build="$ARCH-slackware-linux" || return 1

  make -j"$numjobs" || make || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG"/usr/lib*/*.la || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
