#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr
pkgname=python-nose
pkgver=1.3.7
pkgrel=2slint
slackdesc="$pkgname (a discovery-based unittest extension)"
url='https://readthedocs.org/docs/nose/'
license=('LGPL2.1')
source=(
  "https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz"
)
docs=(NEWS PKG-INFO AUTHORS READMR.txt lgpl) 
build() {
  cd "nose-$pkgver" || return 1
  # setuptools 58 removed support for 2to3
  sed -i "s/'use_2to3': True,//" setup.py
  sed -i 's/from setuptools.command.build_py import Mixin2to3/from distutils.util import Mixin2to3/' setup3lib.py
  2to3 -wn nose unit_tests functional_tests
  python3 setup.py build build_tests
  python3 setup.py install --prefix=/usr --root="$PKG"
  ln -s nosetests "$PKG"/usr/bin/nosetests3
}
