# Sometimes dialog can be corrupted when drawn
# I find rxvt works best when using urxvt + screen
# You may want to try 'xterm', 'xterm-256color' or
# comment it out.
TERM=rxvt

# Dialog colours or not
# Set to "" for no colour
# Default = "--colors"
# The settings in the line below have been adapted for users of a screen reader.
DIALOGOPTS="--no-lines --no-cancel --no-ok --visit-items"

# If you have a custom theme then edit the next line:
export DIALOGRC=~/.soma/dialogrc

#o To try my green theme uncomment the next line:
# export DIALOGRC=~/.soma/greenrc

# Output card
OUTCARD="alsa"

# Balance the volume between Radio 3 and the others.
# Radio 3 has much lower output. This setting boosts
# the Radio 3 volume to a better value. You can set
# this to a value of -200dB to +60dB.
# Also needs and sets -softvol. Set to "" to turn off.
# Default = "-softvol -af volume=8"
AFFILTER="-softvol -af volume=8"

# Whether to use -softvol which keeps mplayer volume isoloated
# from other sounds' volume. Set to "" to use normal hardware
# volume. Note that ( ) volume keys only work with -softvol
SOFTVOL="-softvol"

# CURSOROFF (Turn Off Cursor)
#
# Allowed values: 0 or 1
#
# Default: 1
CURSOROFF=1

# DIALOGFIX (Try To Fix Dialog Drawing Issues By Setting TERM)
#
# If you are experiencing problems with screen drawing this may help.
# You will probably need to restart soma to see any effect.
#
# Allowed values: 0 or 1
#
# Default: 0
DIALOGFIX=0

# TITLECOL (Dialog Title Colour Code)
#
# This setting controls the dialog title colour separate to the
# DIALOGRC settings if needed.
#
# By default it is set to \Zb (bold default dialog foreground colour).
# You can mix bold and colour by eg: \Zb\Z4 etc. See man dialog for
# more info.
#
# Colours are set by \Zn where n =
#
# 0 black
# 1 red
# 2 green
# 3 yellow
# 4 blue
# 5 magenta
# 6 cyan
# 7 white
# 8 default dialogrc foreground
#
# Default: "\Zb"
TITLECOL=""

# SETVOL (Saved Volume From Last Session)
#
# Automatically overwritten
#
# Default: 50
SETVOL=50

# BALANCE (Saved Volume Balance From Last Session)
#
# Automatically overwritten
#
# Default: 0
BALANCE=0

# FILTER (MPlayer Audio Filter)
#
# Set mplayer audio filter (Used with -af)
# Example: "channels=2" can force single channel mono into 2 channel mono.
# See man mplayer for more details.
#
# Default: ""
FILTER=""

# CACHE (MPlayer Cache)
#
# Adjust this if you get drop outs.
#
# Default: 320
CACHE=320

# SAVETRACKLIST (Keep An Ongoing Track List)
#
# The list is located at ~/.soma/tracklist
# Allowed values: 0 or 1
#
# Default: 0
SAVETRACKLIST=0

# GENRE (Your Current Genre)
#
# Saved genre
#
# Default: "All"
GENRE="Classical Music"

# CONNECTTIMEOUT (Connection Timeout)
#
# This controls how long soma will wait for a stream before giving up.
# If you have problems with your internet you may want to adjust it.
#
# Default: 150
CONNECTTIMEOUT=150

# TIMEFORMAT (Format for time display)
#
# This controls how the time is displayed in the status window.
# It defaults to 12 hour format.
# You can change it here.
# Example: 24 hour format would be "%H:%M"
# See the date man page for full options.
#
# Default: "%I:%M"
TIMEFORMAT="%I:%M"

# CARET (Caret Character Used In Menus)
#
# This is the character(s) used in listings.
# Do not use an empty string!
# If you have a utf8 supported terminal, you may want to try "——>"
#
# Default: "-->"
CARET="-->"

# SETTERMTITLE (Set The Terminal/Screen Title to "soma")
#
# Allowed values: 0 or 1
#
# Default: 1
SETTERMTITLE=1

# AUTORECONNECT (Autoreconnect to Lost Streams)
#
# Allowed values: 0 or 1
#
# Default: 0
AUTORECONNECT=0

# SHOWAUDIOINFO (Show Audio and Codec in Stream Info)
#
# Allowed values: 0 or 1
#
# Default: 1
SHOWAUDIOINFO=1

# SHOWVOLUME (Show Current Volume in Title Bar)
#
# Allowed values: 0 or 1
#
# Default: 1
SHOWVOLUME=1

# MENCODEROPTS (Mencoder Source Options For Recording)
#
# See --record-info for info.
#
# Default: "-demuxer rawvideo -rawvideo w=1:h=1 -ovc copy -of rawaudio -audiofile"
MENCODEROPTS="-demuxer rawvideo -rawvideo w=1:h=1 -ovc copy -of rawaudio -audiofile"

# MENCODEROAC (Mencoder Output Audio Codec)
#
# See --record-info for info.
#
# Default: "-oac copy"
MENCODEROAC="-oac copy"

# AUTOSETBITRATE (Try to Set The Bitrate Automatically)
#
# If lavc is used then try to get the source bitrate and apply it
# to the output encoding.
#
# Default: 1
AUTOSETBITRATE=1

# RECEXT (Mencoder Output File Extension)
#
# mp3, mp2, ac3, aac etc.
#
# Default: "mp3"
RECEXT="mp3"

# AUTOSETRECEXT (Try To Set Output File Extension)
#
# Try to set RECEXT automatically.
#
# Default: 1
AUTOSETRECEXT=1

# MT (Popup Message Timeout)
#
# Timeout for message windows in seconds.
#
# Default: 3
MT=3

# MIXER (Audio Mixer)
#
# If you need to set a custom mixer device it can be done here.
#
# Default: 0
MIXER=0

# PROXY (HTTP Proxy)
#
# HTTP Proxy for mplayer and mencoder to use.
#
# Default: ""
PROXY=""
