#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Adapted to Slint by Didier Spaier diideratslintdotfr

pkgname=python3-pyperclip
pkgver=1.9.0
pkgrel=1slint
source=(
  "https://files.pythonhosted.org/packages/source/p/pyperclip/pyperclip-${pkgver}.tar.gz"
)
slackdesc="$pkgname (A cross-platform clipboard module for Python)"
url="https://github.com/asweigart/pyperclip"
license=('BSD-3-Clause')
# GTK/Qt tests crash xvfb, and Klipper tests require a running klipper
#checkdepends=('xorg-server-xvfb' 'python-pytest' 'xsel' 'xclip')
docs=("LICENSE.txt" "README.md")
build() {
  cd "$SRC/pyperclip-$pkgver" || return 1
  python3 -m build --wheel --skip-dependency-check --no-isolation || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1
}

# vim:set ts=2 sw=2 et:
