#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

pkgname=atkmm
pkgver=2.28.2
pkgrel=2slint
url="https://download.gnome.org/sources/atkmm/2.28/"
source=("https://download.gnome.org/sources/${pkgname}/2.28/${pkgname}-${pkgver}.tar.xz")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"atkmm (C++ bindings for ATK)"
""
"atkmm provides the C++ bindings for the ATK library."
""
"Homepage: https://www.gtkmm.org/"
)

build() {
  cd "$SRC/$pkgname-$pkgver" || return 1

  meson setup meson-build . \
    --prefix=/usr \
    --libdir="lib${LIBDIRSUFFIX}" \
    --libexecdir=/usr/libexec \
    --bindir=/usr/bin \
    --sbindir=/usr/sbin \
    --includedir=/usr/include \
    --datadir=/usr/share \
    --mandir=/usr/man \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release || return 1
  "${NINJA:=ninja}" -C meson-build -j "$numjobs" || return 1
  DESTDIR="$PKG" "$NINJA" -C meson-build install || return 1

  mkdir -p "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  cp -a AUTHORS COPYING* NEWS README* "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  if [[ -r ChangeLog ]]; then
    head -n 1000 ChangeLog > "$PKG/usr/doc/$pkgname-$pkgver/ChangeLog" || return 1
    touch -r ChangeLog "$PKG/usr/doc/$pkgname-$pkgver/ChangeLog" || return 1
  fi
}
