#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-Net-SSLeay
pkgver=1.92
pkgrel=1slint
depends=("openssl|openssl-solibs" "zlib")
export srcname=Net-SSLeay
source=("https://cpan.metacpan.org/authors/id/C/CH/CHRISN/$srcname-$pkgver.tar.gz")
docs=("Changes" "Credits" "README" "examples")
url="https://metacpan.org/pod/Net::SSLeay"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-Net-SSLeay (OpenSSL support for Perl)"
"Net::SSLeay provides high-level HTTPS helpers and access"
"to the OpenSSL API from Perl."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  printf 'n\n' | perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN1DIR=/usr/man/man1 \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
