#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python3-twisted
srcname=Twisted
export srcname
pkgver=21.2.0
pkgrel=1slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Python networking engine)"
""
"Twisted is an event-driven networking engine written in"
"Python."
""
"Homepage: https://twistedmatrix.com/"
)
url="https://twistedmatrix.com/"
depends=("python3")
makedepends=("python-build" "python3-installer" "python-wheel")
source=("https://files.pythonhosted.org/packages/source/T/${srcname}/${srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  local docDir

  cd "$SRC/${srcname}-${pkgver}" || return 1

  python3 -m build --wheel --no-isolation || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1

  docDir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docDir" || return 1

  shopt -s nullglob
  for doc in LICENSE* NEWS* README*; do
    [[ -e $doc ]] || continue
    cp -a "$doc" "$docDir/" || return 1
  done
  shopt -u nullglob
}
