#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Felix Yan <felixonmars@archlinux.org>
# Maintainer: Levente Polyak <anthraxx[at]archlinux[dot]org>
# Contributor: Lex Black <autumn-wind at web dot de>
# Contributor: TingPing <tingping@tingping.se>
# Contributor: Guillaume Horel <guillaume.horel@gmail.com>
# Included in Slint by Didier Spaier didieratslintdotfr

pkgbase=brotli
export pkgbase
pkgname=python3-brotli
_gitcommit=ed738e842d2fbdf2d6459e39267a633c4a9b2f5d
pkgver=1.0.9
pkgrel=1slint
slackdesc="$pkgname (python bindings for the brotli algorithm)"
url='https://github.com/google/brotli'
arch=('x86_64')
license=('MIT')
makedepends=(
  cmake
  python3-setuptools
  python3-build
  python3-installer
  python3-wheel
)
source=("https://github.com/google/brotli/archive/refs/tags/v${pkgver}.tar.gz")
sha512sums=('SKIP')
docs=('LICENSE')
options=("nosrcpack")
build() {
  cd "${pkgbase}-${pkgver}" || return 1
  python3 -m build --wheel --no-isolation || return 1
  cmake -S . -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS=True \
    -DCMAKE_C_FLAGS="$CFLAGS -ffat-lto-objects"
  cmake --build build -v
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1
}
