#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Packager: sektor

pkgname=psutil
pkgver=5.8.0
_srcname="${pkgname}-release-${pkgver}"
pkgrel=2slint
source=("https://github.com/giampaolo/psutil/archive/release-${pkgver}/${_srcname}.tar.gz")
url="https://github.com/giampaolo/psutil"
docs=("*.rst" "LICENSE" "CREDITS")
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"psutil: psutil (python interface for process and system info)"
)

build() {
  cd "${_srcname}" || return 1
  # Remove shebangs from installed Python sources.
  find psutil -name "*.py" | while read -r line; do
    sed -i.orig '/^#!/d' "$line"
    touch -r "${line}.orig" "$line"
    rm "${line}.orig"
  done
  python3 setup.py install --root="$PKG"
}
