diff -ru ansifilter-2.17/makefile ansifilter-2.17.new/makefile
--- ansifilter-2.17/makefile	2020-09-29 23:31:42.000000000 +0200
+++ ansifilter-2.17.new/makefile	2020-10-21 19:13:22.072498261 +0200
@@ -4,7 +4,7 @@
 # Installation directories:
 
 # Destination directory for installation (intended for packagers)
-DESTDIR = 
+DESTDIR = $PKG
 
 # Root directory for final installation
 PREFIX = /usr
@@ -13,10 +13,10 @@
 bin_dir = ${PREFIX}/bin/
 
 # Location of the man page:
-man_dir = ${PREFIX}/share/man/man1/
+man_dir = ${PREFIX}/man/man1/
 
 # Location of the documentation:
-doc_dir = ${PREFIX}/share/doc/ansifilter/
+doc_dir = ${PREFIX}/doc/ansifilter-$pkgver/
 
 # Location of additional gui files
 desktop_apps = ${PREFIX}/share/applications/
@@ -24,7 +24,7 @@
 
 # Commands:
 GZIP=gzip -9f
-QMAKE=qmake
+QMAKE=/usr/lib64/qt/bin/qmake
 
 INSTALL_DATA=install -m644
 INSTALL_PROGRAM=install -m755
