#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-Try-Tiny
pkgver=0.31
pkgrel=1slint
export srcname=Try-Tiny
source=("https://cpan.metacpan.org/authors/id/E/ET/ETHER/$srcname-$pkgver.tar.gz")
docs=("Changes")
url="https://metacpan.org/pod/Try::Tiny"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-Try-Tiny (minimal try/catch for Perl)"
"Try::Tiny provides minimal try/catch with proper"
"localization of \$@."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN1DIR=/usr/man/man1 \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
