#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-Encode-JISX0213
pkgver=0.04
pkgrel=2slint
depends=("perl-Encode-ISO2022")
export srcname=Encode-JISX0213
source=("https://cpan.metacpan.org/authors/id/N/NE/NEZUMI/$srcname-$pkgver.tar.gz")
docs=("Changes" "README")
url="https://metacpan.org/pod/Encode::JISX0213"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-Encode-JISX0213 (JIS X 0213 encoding modules)"
"Encode::JISX0213 provides JIS X 0213 and related"
"encodings."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  # Older bundled inc::Module::Install loaders expect . in @INC.
  export PERL_USE_UNSAFE_INC=1
  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
