.TH XML2 1 "7h february 2008"
.SH NAME
xml2 \- convert xml documents in a flat format

2xml \- convert flat format into xml

html2 \- convert html documents in a flat format

2html \- convert flat format into html

csv2 \- convert csv files in a flat format

2csv \- convert flat format into csv
.SH SYNOPSIS
<xml2|2xml|html2|2html|csv2|2csv> > outfile < infile


.SH DESCRIPTION
There are six tools. Except csv2 and and 2csv they don't take
any command-line arguments.
They are all simple filters which can be used to read files from
standard input in one format and output it to standard output in
another format.

The flat format used by the tools is specific to these tools.
It is a syntax for representing structured markup in a way that
makes it easy to process with line-oriented tools.
The same format is used for HTML and XML; in fact, you can think
of html2 as converting HTML to XHTML and running xml2 on the result;
likewise 2html and 2xml. (Of course, this isn't how the implementation works.)
.SH SEE ALSO
This program does normally not include any documentation in form of manpages.
However it has a real excellent documentation online with a lot of example.
In fact this manpage was based on this documentation.

Please find it on:

http://dan.egnor.name/xml2/ref

Examples can be found here:

http://dan.egnor.name/xml2/examples
.SH AUTHOR
xml2 was written by Dan Egnor.

This manpage was written by Patrick Schoenfeld <schoenfeld@in-medias-res.com>
for the Debian project, but may be used by others under the same terms as xml2
is distributed.
.SH BUGS
Bugs can be reported through the Debian Bug tracking system.
