#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-data-dump
pkgver=1.25
pkgrel=1slint
export srcname=Data-Dump
source=("https://cpan.metacpan.org/authors/id/G/GA/GARU/$srcname-$pkgver.tar.gz")
docs=("README.md" "Changes")
url="https://metacpan.org/pod/Data::Dump"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-data-dump (pretty printer for Perl data structures)"
"Emits readable Perl code that reconstructs data structure content."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
