#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python-asn1crypto
_srcname=asn1crypto
pkgver=1.4.0
pkgrel=1slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (fast ASN.1 parser and serializer)"
""
"asn1crypto is a fast ASN.1 parser and serializer with"
"support for keys, X.509 certificates, PKCS#12, and more."
""
"Homepage: https://pypi.org/project/asn1crypto/"
)
url="https://pypi.org/project/asn1crypto/"
depends=("python")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/a/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  shopt -s nullglob
  for doc in LICENSE changelog.* docs/*; do
    [[ -e $doc ]] || continue
    cp -a "$doc" "$docdir/" || return 1
  done
  shopt -u nullglob

  find "$docdir" -type f -exec chmod 0644 {} + || return 1
}
