#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Based on Arch packaging; adapted for Slint.

pkgname=python3-pathvalidate
_srcname=pathvalidate
pkgver=3.3.1
pkgrel=1slint
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (sanitize and validate filename/path strings)"
"pathvalidate sanitizes and validates strings used in file names,"
"file paths, symbols, and related user input."
)
url='https://github.com/thombashi/pathvalidate'
license=('MIT')
depends=('python3' 'python3-click')
makedepends=('python3-setuptools-scm' 'python3-wheel' 'python3-installer' 'python3-build')
source=("https://github.com/thombashi/pathvalidate/releases/download/v${pkgver}/${_srcname}-${pkgver}.tar.gz")
sha256sums=('b18c07212bfead624345bb8e1d6141cdcf15a39736994ea0b94035ad2b1ba177')
options=('nosrcpack')

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  python3 -m build --wheel --no-isolation || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1

  install -Dm644 README.rst "$PKG/usr/doc/$pkgname-$pkgver/README.rst" || return 1
  install -Dm644 LICENSE "$PKG/usr/doc/$pkgname-$pkgver/LICENSE" || return 1
}
