#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Felix Yan <felixonmars@archlinux.org>

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python3-hatch-vcs
pkgver=0.5.0
pkgrel=2slint
export srcname=hatch-vcs
slackdesc="$pkgname (Hatch plugin for versioning with your VCS)"
url="https://github.com/ofek/hatch-vcs"
license=('MIT')
depends=('python3-hatchling' 'python3-setuptools-scm')
makedepends=('git' 'python3-build' 'python3-installer')
checkdepends=('python-pytest')
source=("https://github.com/ofek/hatch-vcs/archive/refs/tags/v${pkgver}.tar.gz")
sha512sums=('c987b4e50bd3c53503fb09add9b06d0464b1b75f195906146f5253737f44a7967a83730bc6132c5335ec6ce71554bca47fa3956b08196963fa953395730e689d')
docs=("LICENSE.TXT" "README.md" "HISTORY.md")
build() {
  cd "${srcname}-$pkgver" || return 1
  python3 -m build -nw || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1
}
