#!/bin/sh
# This scripts handle discrepancies between SBo and Slint packages names.
# It is run by remove-unwanted-slackbuilds_data, itself run after execution
# of the command "slapt-src -u"
. /etc/slapt-get/slapt-srcrc
cd $BUILDDIR
sed '
/SLACKBUILD REQUIRES:/{
s/BeautifulSoup4/python-beautifulsoup4/g
s/Net-SSLeay/perl-Net-SSLeay/g
s/python3-attrs/python-attrs/g
s/python3-autobahn/python-autobahn/g
s/python3-automat/python-automat/g
s/python3-babel/python-babel/g
s/python3-dateutil/python-dateutil/g
s/python3-fasteners/python-fasteners/g
s/numpy3/python-numpy/g
s/pyOpenSSL/python-openssl/g
s/python3-pexpect/python-expect/g
s/python3-ptyprocess/python-ptyprocess/g
s/pyalsaaudio/python-pyalsaaudio/g
s/pyasn1/python-pyasn1/g
s/pyasn1-modules/python-pyasn1-modules/g
s/pycryptodomex/python-pycryptodomex/g
s/pyenchant/python-pyenchant/g
s/python3-pyjwt/python-pyjwt/g
s/pylast/python-pylast/g
s/pynacl/python-pynacl/g
s/pyte/python-pyte/g
s/python3-pythran/python-pythran/g
s/pytz/python-pytz/g
s/pyudev/python-pyudev/g
s/scipy3/python-scipy/g
s/python3-semantic-version/python-semantic-version/g
s/python3-service-identity/python-service-identity/g
s/python3-setuptools-rust/python-setuptools-rust/g
s/python3-soupsieve/python-soupsieve/g
s/python3-twisted/python-twisted/g
s/python3-txaio/python-txaio/g
s/python3-wcwidth/python-wcwidth/g
s/python3-websockets/python-websockets/g
s/gusersoundfont/soundfont-generaluser/g
s/python-distutils-extra/python2-distutils-extra python3-distutils-extra/g
s/purple-telegram/telegram-purple/g
s/snowballstemmer/python-snowballstemmer/g
}' slackbuilds_data > bof
mv bof slackbuilds_data

# Sbo Slint.

# pynacl est pour python2 et python3
# pyte est pour python2 et python3
# pytz est pour python2 et python3
