#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Added in Slint Python 3.11 migration

pkgname=python3-cffi
srcname=cffi
export srcname
pkgver=2.0.0
pkgrel=1slint
slackdesc="$pkgname (Foreign Function Interface for Python 3)"
url="https://cffi.readthedocs.io/"
license=("MIT")
arch=("x86_64")
depends=("libffi" "python3" "python3-pycparser")
makedepends=("python3-setuptools" "python3-trove-classifiers")
source=("https://files.pythonhosted.org/packages/source/c/cffi/cffi-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  local docDir
  local docFile

  docDir="$PKG/usr/doc/$pkgname-$pkgver"

  cd "$SRC/${srcname}-${pkgver}" || return 1
  python3 setup.py install --root="$PKG" || return 1

  install -d "$docDir" || return 1
  for docFile in LICENSE *.md *.rst doc; do
    [[ -e "$docFile" ]] || continue
    cp -a "$docFile" "$docDir/" || return 1
  done
}
