#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-Encode-HanExtra
pkgver=0.23
pkgrel=2slint
depends=("perl-Module-Install")
export srcname=Encode-HanExtra
source=("https://cpan.metacpan.org/authors/id/A/AU/AUDREYT/$srcname-$pkgver.tar.gz")
docs=("README" "Changes")
url="https://metacpan.org/pod/Encode::HanExtra"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-Encode-HanExtra (extra Chinese encodings)"
"Encode::HanExtra adds extra Chinese encodings beyond"
"core Perl."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  # Older bundled inc::Module::Install loaders expect . in @INC.
  export PERL_USE_UNSAFE_INC=1
  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
