#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-Cairo-GObject
pkgver=1.005
pkgrel=1slint
depends=(
  "aaa_libraries|bzip2"
  "aaa_libraries|glib2"
  "aaa_libraries|libffi"
  "aaa_libraries|libpng"
  "aaa_libraries|pcre"
  "aaa_libraries|xz"
  "brotli"
  "cairo"
  "fontconfig"
  "freetype"
  "graphite2"
  "harfbuzz"
  "libX11"
  "libXau"
  "libXdmcp"
  "libXext"
  "libXrender"
  "libglvnd"
  "libxcb"
  "libxml2"
  "pixman"
  "zlib"
)
export srcname=Cairo-GObject
source=("https://cpan.metacpan.org/authors/id/X/XA/XAOC/$srcname-$pkgver.tar.gz")
docs=("NEWS" "README")
url="https://metacpan.org/pod/Cairo::GObject"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-Cairo-GObject (register Cairo types with Glib)"
"Cairo::GObject integrates Cairo objects with the Glib"
"type system."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN1DIR=/usr/man/man1 \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
