#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

pkgname=gst-plugins-base
pkgver=1.28.1
pkgrel=1slint
url="https://gstreamer.freedesktop.org/"
license=("LGPL-2.1-or-later")
source=("https://gstreamer.freedesktop.org/src/gst-plugins-base/${pkgname}-${pkgver}.tar.xz")
options=("nosrcpack")
docs=("AUTHORS*" "COPYING*" "NEWS*" "README*" "RELEASE*")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"gst-plugins-base (base set of GStreamer plugins)"
""
"Core GStreamer plug-ins and helper libraries."
"This package provides the essential audio and video elements,"
"base classes, and libraries used by higher-level plug-ins."
)

build() {
  local docsDir

  docsDir="$PKG/usr/doc/$pkgname-$pkgver"

  cd "$SRC/$pkgname-$pkgver" || return 1

  meson setup buildDir \
    --prefix=/usr \
    --libdir="lib${LIBDIRSUFFIX}" \
    --libexecdir=/usr/libexec \
    --bindir=/usr/bin \
    --sbindir=/usr/sbin \
    --includedir=/usr/include \
    --datadir=/usr/share \
    --mandir=/usr/man \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Dbenchmarks=disabled \
    -Dexamples=disabled || return 1

  meson compile -C buildDir -j "$numjobs" || return 1
  DESTDIR="$PKG" meson install -C buildDir || return 1

  install -Dm0644 "$SRC/../SLKBUILD" "$docsDir/SLKBUILD" || return 1
}
