#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-Glib-Object-Introspection
pkgver=0.049
pkgrel=1slint
depends=(
  "aaa_libraries|glib2"
  "aaa_libraries|libffi"
  "aaa_libraries|pcre"
  "glib2"
  "gobject-introspection"
  "util-linux"
  "zlib"
)
export srcname=Glib-Object-Introspection
source=("https://cpan.metacpan.org/authors/id/X/XA/XAOC/$srcname-$pkgver.tar.gz")
docs=("LICENSE" "NEWS" "README*")
url="https://metacpan.org/pod/Glib::Object::Introspection"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-Glib-Object-Introspection (Perl GI bindings)"
"Glib::Object::Introspection dynamically creates"
"Perl language bindings from introspection data."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
