1. Introduction

Flatpak is a framework for desktop applications on Linux. It allows to install
in Slint applications not available as regular packages, or of a more recent
version, or difficult to build for Slint.

CAVEATS
1. The applications installed via flatpak can only be managed by flatpak, not
by the usual packages management tools. However they can be started from the
Applications menu of the desktop.
2. The applications installed via flatpak, along with their dependencies, are
very huge (several hundreds of megabytes for the simpler ones), so you need a
lot of space on disk to install them. If you install applications in your
$HOME (see 'user' mode below) you need enough free space in $HOME.
This can be an issue if /home in its own partition (which is not the default
in a Slint installation).

The flatpaks can be installed in 'system' in /var/lib/flatpak or in 'user'
mode ~/.local/share/flatpak for a specific user. The latter is recommended.

You can find many apps already available on https://flathub.org/
The flathub repository is enabled system-wide ('system' mode) in Slint upon
flatak installation.
to access the flathub also in 'user' mode you need to enable the flathub
repository as 'user'

To do this type as regular user (not as root!) this command:
flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

You only need to do that once.

Then, to manage flatpaks in 'user' mode, always include the --user or -u
option in flatpak commands.

ACCESSIBILITY

To make more accessible Thunderbird, Firefox and many other Flatpak applications,
run as regular user:
make-flatpak-accessible

You only need to do that once.

2. Example.

Let's assume that you want to install the text editor abiword.

You can use the search feature of https://flathub.org/ but it could be hardly
accessible using a screen reader. Instead you can just type commands, as
regular user (this is mandatory in 'user' mode).

Just type:
flatpak -u install abiword
The output is:
Found ref ‘app/com.abisource.AbiWord/x86_64/stable’ in remote ‘flathub’ (user).
Use this ref? [Y/n]:

Then type Y or just press Enter to confirm.
Ayou are then asked:
Required runtime for com.abisource.AbiWord/x86_64/stable (runtime/org.gnome.Platform/x86_64/47) found in remote flathub
Do you want to install it? [Y/n]:
Again, tye Y or press Enter
Then you get a new output like this:
Do you want to install it? [Y/n]: 

com.abisource.AbiWord permissions:
    ipc     network     fallback-x11     wayland    x11    file access [1]    dbus access [2]

    [1] home, xdg-run/gvfs, xdg-run/gvfsd
    [2] org.gtk.vfs.*


        ID                                              Branch                Op            Remote             Download
 1.     com.abisource.AbiWord.Locale                    stable                i             flathub              < 2,0 Mo (partial)
 2.     org.freedesktop.Platform.GL.default             24.08                 i             flathub            < 156,3 Mo
 3.     org.freedesktop.Platform.GL.default             24.08extra            i             flathub            < 156,3 Mo
 4.     org.freedesktop.Platform.VAAPI.Intel            24.08                 i             flathub             < 14,7 Mo
 5.     org.freedesktop.Platform.openh264               2.4.1                 i             flathub            < 976,5 ko
 6.     org.gnome.Platform.Locale                       47                    i             flathub            < 386,5 Mo (partial)
 7.     org.gnome.Platform                              47                    i             flathub            < 384,7 Mo
 8.     com.abisource.AbiWord                           stable                i             flathub             < 16,5 Mo

Proceed with these changes to the user installation? [Y/n]: 

This tells which permissions are needed by abiword and the needed dependencies
that will also be installed if you agree. You can check the sizes of the files
to download (and yes they are huge as abiword needs a lot of files from the
Gnome desktop)

If you accept, again typing Y or just pressing Enter all dependencies are
fetched from flathub.org, then Abiword itself. The last line of output is:
Installation complete.

As soon as done the application is available from the desktop menu, accessible
pressing F1.

Or to find it press the left Windows(Super) key and type the first few letters
of the application’s name. Then, use the down arrow to view all applications
starting with those letters in a drop down list. Navigate ro the one you want
then, press Enter to start it.

In the example the application can also be started typing:
flatpak run com.abisource.AbiWord

the argument of 'flatpak run' should be the application ID. To find it type:
flatpak -u --columns=application,name list
The application iD is the one on the same coulumn as the name AbiWord.

3. Documentation

There is an integrated help, accessed typing:
flatpak --help

To know te details for one of the commands listed, like 'uninstall', type:
flatpak uninstall --help

The reference is the docs.flatpak.org website. To begin with, read:
https://docs.flatpak.org/en/latest/getting-started.html
and especially:
https://docs.flatpak.org/en/latest/using-flatpak.html

4. Alternatively, get packages as Appimages

There is another way to get software not available as packages which is to
download a so-called AppImage (no installation necessary). For a short
explanation, read https://docs.appimage.org/introduction/index.html

I am not aware of a centralized repository for AppImages but you can use a do
a web search with as arguments AppImage and the name of the software you want
Be very careful to only get one from a repository you trust and preferably get
it from the web site of this software.
