#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Benjamin Trigona-Harany <slackbuilds@jaxartes.net>
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python-pexpect
pkgver=4.8.0
pkgrel=2slint
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Python 3 module for spawning child applications)"
""
"$pkgname is a Python module for spawning child applications,"
"controlling them, and responding to expected patterns in their"
"output. It can be used for automating interactive applications"
"such as ssh, ftp, passwd, telnet, etc."
"$pkgname is pure Python."
)
url="https://github.com/pexpect/pexpect"
license=("ISC")
depends=("python" "python-ptyprocess")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/p/pexpect/pexpect-$pkgver.tar.gz")
docs=("LICENSE" "README.rst")
options=("nosrcpack")

build() {
  cd "$SRC/pexpect-$pkgver" || exit 1
  python3 setup.py install --root="$PKG" || exit 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  legacy_suffix=SlackBuild
  mkdir -p "$docdir"
  cp -a LICENSE README.rst "$docdir" || exit 1
  install -m 0644 "$SRC/../SLKBUILD" "$docdir/$pkgname.$legacy_suffix"
}
