#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=atk
pkgver=2.38.0
pkgrel=1slint
url="https://download.gnome.org/sources/atk/2.38/"
source=("https://download.gnome.org/sources/${pkgname}/2.38/${pkgname}-${pkgver}.tar.xz")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"atk (accessibility functions library)"
""
"atk is a library of accessibility functions used by GTK."
""
"Homepage: https://download.gnome.org/sources/atk/2.38/"
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  meson setup meson-build \
    --prefix=/usr \
    --libdir="lib${LIBDIRSUFFIX}" \
    --libexecdir=/usr/libexec \
    --bindir=/usr/bin \
    --sbindir=/usr/sbin \
    --includedir=/usr/include \
    --datadir=/usr/share \
    --mandir=/usr/man \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Dintrospection=true \
    -Ddocs=true \
    . || return 1
  "${NINJA:=ninja}" -C meson-build -j "$numjobs" || return 1
  DESTDIR="$PKG" "$NINJA" -C meson-build install || return 1

  rm -f "$PKG"/{,usr/}lib"${LIBDIRSUFFIX}"/*.la || return 1

  mkdir -p "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  cp -a AUTHORS COPYING* NEWS README* TODO "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  if [[ -r ChangeLog ]]; then
    head -n 1000 ChangeLog > "$PKG/usr/doc/$pkgname-$pkgver/ChangeLog" || return 1
    touch -r ChangeLog "$PKG/usr/doc/$pkgname-$pkgver/ChangeLog" || return 1
  fi
  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
