The matchbox graphical environment is described in:
/usr/doc/matchbox/matchbox-manual.html, partially outdated.

The matchbox graphical environment in Slint provides the minimum of
components necessary to run graphical applications. As such it can be
useful for people who prefer to use the command line but need to run a
graphical application occasionally, for instance to browse the web with
javascript enabled.

Slint ships these components as packages:
matchbox-common-0.9.1-x86_64-1slint.txz
  Virtual folders (categories) for matchbox-destop
matchbox-desktop-2.2-x86_64-1slint.txz
  Displays icons to launch applications sorted by category in a window.
matchbox-terminal-0.2-x86_64-1slint.txz
  Very light terminal
matchbox-themes-extra-0.4-x86_64-1slint.txz
  Additional themes for the windows
matchbox-window-manager-1.2.2-x86_64-2slint.txz
  Window manager that displays one window at a time, always maximized.
  
Screen layout
The screen displays a background, one window at a time and optionally
the onboard on screen keyboard and the plank dock. The orca screen reader
can also be used, making matchbox accessible with speech and braille.
To start initially plank, orca screen reader or onboard in matchbox,
type: plank-on, orca-on, onboard-on respectively. To not start them
initially type instead plank-off, orca-off, onboard-off, respectively.
I recommend to include in plank at least  the docklets applications,
clippy, clock, and notifications 

Keyboard shortcuts
The default keyboard shortcuts are written in /etc/matchbox/kbdconfig,
so to know them read this file.
To customize them for a given user copy this file in the $HOME directory
like this:
mkdir -p ~./matchbox
cp /etc/matchbox/kbdconfig ~/.matchbox
then edit the file ~/.matchbox/kbdconfig

How to start matchbox
As with the other graphical environments if you login in text mode,
select it typing: session-chooser matchbox, then start it typing startx.
If you use lightdm, just select it among the available sessions.

If you want to customize the way matchbox starts:
- from text mode, edit as root the file /etc/X11/xinit.matchbox
- from lightdm, start it from lightdm. This will copy the init script in
  $HOME as ~/.matchbox/startup. Then edit the file ~/.matchbox/startup
Be careful when editing these files!
