#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Slackware Python Team
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python-certifi
_srcname=certifi
pkgver=2021.10.8
pkgrel=1slint
source=("https://files.pythonhosted.org/packages/source/c/certifi/certifi-$pkgver.tar.gz")
url="https://certifi.io/"
license=("MPL-2.0")
depends=("python")
makedepends=("python-setuptools")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Python package for Mozilla's CA bundle)"
""
"Certifi is a carefully curated collection of Root Certificates"
"for validating the trustworthiness of SSL certificates while"
"verifying the identity of TLS hosts."
""
"Homepage: https://certifi.io/"
)

build() {
  cd "$SRC/$_srcname-$pkgver" || exit 1

  python3.9 setup.py install --root="$PKG" || exit 1
  python3.11 setup.py install --root="$PKG" || exit 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  mkdir -p "$docdir"
  cp -a ./*.rst LICENSE PKG-INFO "$docdir" || exit 1
}
