#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-lwp-useragent-cached
pkgver=0.08
pkgrel=2slint
export srcname=LWP-UserAgent-Cached
source=("https://cpan.metacpan.org/authors/id/O/OL/OLEG/$srcname-$pkgver.tar.gz")
docs=("README" "Changes")
url="https://metacpan.org/release/LWP-UserAgent-Cached"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-lwp-useragent-cached (filesystem cache for LWP::UserAgent)"
"Returns cached HTTP responses from local storage when available."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN1DIR=/usr/man/man1 \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
