#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=vo-amrwbenc
pkgver=0.1.3
pkgrel=2slint
source=("https://downloads.sourceforge.net/project/opencore-amr/vo-amrwbenc/vo-amrwbenc-${pkgver}.tar.gz")
url="https://sourceforge.net/projects/opencore-amr/"
license=("Apache")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"vo-amrwbenc (VisualOn amr wideband encoder library)"
""
"VisualOn AMR-WB encoder library."
""
"vo-amrwbenc home: https://sourceforge.net/projects/opencore-amr/"
)

build() {
  cd "$SRC/$pkgname-$pkgver" || return 1

  LDFLAGS="$SLKLDFLAGS" \
  CFLAGS="$SLKCFLAGS" \
  CXXFLAGS="$SLKCFLAGS" \
  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/man \
    --disable-static \
    --docdir="/usr/doc/$pkgname-$pkgver" \
    --build="$ARCH-slackware-linux" || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG/usr/lib${LIBDIRSUFFIX}"/*.la || return 1

  install -d "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  cp -a ChangeLog README NOTICE COPYING "$PKG/usr/doc/$pkgname-$pkgver/" || return 1
  install -Dm0644 "$startdir/SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.SlackBuild" || return 1
}
