#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

pkgname=gstreamer
pkgver=1.28.1
pkgrel=2slint
url="https://gstreamer.freedesktop.org/"
license=("LGPL-2.1-or-later")
source=("https://gstreamer.freedesktop.org/src/gstreamer/${pkgname}-${pkgver}.tar.xz")
options=("nosrcpack")
docs=("AUTHORS*" "COPYING*" "NEWS*" "README*" "RELEASE*")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"gstreamer (streaming multimedia framework)"
""
"GStreamer lets you build graphs of media components."
"From simple audio playback to complex audio/video processing,"
"applications benefit from codec advances and filter technology."
"Developers add new codecs and filters via plug-ins."
)

build() {
  local docsDir

  docsDir="$PKG/usr/doc/$pkgname-$pkgver"

  cd "$SRC/$pkgname-$pkgver" || return 1

  meson setup buildDir \
    --prefix=/usr \
    --libdir="lib${LIBDIRSUFFIX}" \
    --libexecdir=/usr/libexec \
    --bindir=/usr/bin \
    --sbindir=/usr/sbin \
    --includedir=/usr/include \
    --datadir=/usr/share \
    --mandir=/usr/man \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Dbenchmarks=disabled \
    -Ddoc=disabled \
    -Dexamples=disabled \
    -Dtests=disabled \
    -Dglib_debug=disabled \
    -Dcoretracers=enabled || return 1

  meson compile -C buildDir -j "$numjobs" || return 1
  DESTDIR="$PKG" meson install -C buildDir || return 1

  install -Dm0644 "$SRC/../SLKBUILD" "$docsDir/SLKBUILD" || return 1
}
