#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python3-six
srcname=six
export srcname
pkgver=1.17.0
pkgrel=2slint
source=("https://files.pythonhosted.org/packages/source/s/${srcname}/${srcname}-${pkgver}.tar.gz")
url="https://pypi.org/project/six/"
license=("MIT")
depends=("python3")
makedepends=("python3-setuptools")
docs=("CHANGES" "LICENSE" "PKG-INFO" "README" "documentation")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Python 2 and 3 compatibility library)"
""
"Six provides utility functions for smoothing over the"
"differences between Python 2 and Python 3 with a single"
"small runtime module."
""
"Homepage: https://pypi.org/project/six/"
)

build() {
  local docDir

  cd "$SRC/${srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docDir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docDir" || return 1

  shopt -s nullglob
  for docFile in CHANGES LICENSE PKG-INFO README documentation; do
    [[ -e "$docFile" ]] || continue
    cp -a "$docFile" "$docDir/" || return 1
  done
  shopt -u nullglob
}
