#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Storm Dragon <storm_dragon@stormux.org>

pkgname=python3-miniirc
_srcname=miniirc
pkgver=1.10.0
pkgrel=2slint
slackdesc="$pkgname (A straightforward IRC client library for Python)"
url="https://github.com/luk3yx/miniirc"
license=('MIT')
depends=('python3')
makedepends=('python3-build' 'python3-installer' 'python3-wheel' 'python3-setuptools')
optdepends=('python3-certifi: for SSL certificate verification')
options=('nosrcpack')
source=("https://files.pythonhosted.org/packages/source/m/miniirc/$_srcname-$pkgver.tar.gz")
sha256sums=('9811ed325924359be622563510842715012f7c7b23430545cfdeb7ff80e2eaf8')
docs=(LICENSE README.md)

build() {
  cd "$SRC/$_srcname-$pkgver" || exit 1
  python3 -m build --wheel --no-isolation || exit 1
  python3 -m installer --destdir="$PKG" dist/*.whl || exit 1
}
