#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-Role-Tiny
pkgver=2.002004
pkgrel=1slint
export srcname=Role-Tiny
source=("https://cpan.metacpan.org/authors/id/H/HA/HAARG/$srcname-$pkgver.tar.gz")
docs=("Changes")
url="https://metacpan.org/pod/Role::Tiny"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-Role-Tiny (minimalist role composition)"
"Role::Tiny provides a small, lightweight role"
"composition tool for Perl."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
