#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python-constantly
_srcname=constantly
pkgver=15.1.0
pkgrel=1slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (symbolic constants in Python)"
""
"A library that provides symbolic constant support, including"
"collections and constants with text, numeric, and bit-flag"
"values."
""
"Homepage: https://pypi.org/project/constantly/"
)
url="https://pypi.org/project/constantly/"
depends=("python")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/c/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  shopt -s nullglob
  for doc in LICENSE *.rst; do
    [[ -e $doc ]] || continue
    cp -a "$doc" "$docdir/" || return 1
  done
  shopt -u nullglob
}
