#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: Didier Spaier didieratslintdotfr

pkgname=at-spi2-core
pkgver=2.58.1
pkgrel=2slint
source=("https://download.gnome.org/sources/$pkgname/2.58/$pkgname-$pkgver.tar.xz")
docs=("AUTHORS" "COPYING" "INSTALL" "NEWS" "README.md")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"at-spi2-core: at-spi2-core (AT-SPI2 service provider core)"
"at-spi2-core:"
"at-spi2-core: Part of GNOME Accessibility. Provides an SPI for"
"at-spi2-core: assistive technologies on the GNOME platform."
"at-spi2-core:"
"at-spi2-core:"
"at-spi2-core:"
"at-spi2-core:"
"at-spi2-core:"
)

doinst() {
if compgen -G '/var/lib/pkgtools/packages/at-spi2-atk-*' >/dev/null; then
  /sbin/removepkg at-spi2-atk
fi
if compgen -G '/var/lib/pkgtools/packages/atk-*' >/dev/null; then
  /sbin/removepkg atk
fi
}

build() {
  cd "$SRC/$pkgname-$pkgver" || exit 1
  export CFLAGS="$SLKCFLAGS"
  export CXXFLAGS="$SLKCFLAGS"

  meson setup \
    --prefix=/usr \
    --libdir="lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/man \
    -Dpython=python3.11 \
    build || exit 1

  meson compile -C build -j "$numjobs" || exit 1
  DESTDIR="$PKG" meson install -C build || exit 1
}
