#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-File-ShareDir
pkgver=1.102
pkgrel=1slint
arch=noarch
depends=("perl-Class-Inspector" "perl-File-ShareDir-Install")
export srcname=File-ShareDir
source=("https://cpan.metacpan.org/authors/id/R/RE/REHSACK/$srcname-$pkgver.tar.gz")
docs=("Changes" "MANIFEST")
url="https://metacpan.org/pod/File::ShareDir"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-File-ShareDir (locate module shared files)"
"File::ShareDir locates per-distribution and"
"per-module shared files after installation."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
