#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python3-evdev
srcname=evdev
export srcname
pkgver=1.9.3
pkgrel=1slint
slackdesc="$pkgname (Python 3 input event library)"
url="https://python-evdev.readthedocs.io/en/latest/"
license=("BSD")
arch=("x86_64")
depends=("python3")
makedepends=("python3-build" "python3-installer" "python3-wheel")
source=("https://files.pythonhosted.org/packages/source/e/evdev/evdev-${pkgver}.tar.gz")
docs=("LICENSE" "README.rst")
options=("nosrcpack")

build() {
  cd "$SRC/${srcname}-${pkgver}" || return 1

  # Upstream shipped some releases with mode 660 files in the tarball.
  find -L . -perm 660 -exec chmod 644 {} + || return 1

  python3 -m build --wheel --no-isolation || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1
}
