#!/bin/bash
# shellcheck shell=bash disable=SC2034

pkgname=python3-spake2
export srcname=spake2
pkgver=0.8
pkgrel=3slint

source=("https://files.pythonhosted.org/packages/source/s/${srcname}/${srcname}-${pkgver}.tar.gz")
url="https://pypi.org/project/spake2/"
docs=("NEWS" "LICENSE" "README.md")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (SPAKE2 password-authenticated key exchange)"
"This library implements the SPAKE2 password-authenticated key exchange"
)
build() {
  cd "$SRC/${srcname}-${pkgver}" || return 1
  rm -rf build
  python3 setup.py install --root="$PKG" || return 1
}
