#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libaom
pkgver=1.0.0.r1804.gcb43f766c
pkgrel=2slint
url="https://aomedia.googlesource.com/aom"
license=("BSD-2-Clause")
source=("https://www.andrews-corner.org/downloads/SBo/${pkgname}-${pkgver}.tar.gz")
docs=("AUTHORS" "CHANGELOG" "LICENSE" "PATENTS" "README.md")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"libaom (Open Source Video Codec)"
""
"AOMedia Video 1 (AV1) is designed to be the successor to VP9 and"
"also to eventually be a direct competitor for HEVC/H.265."
""
""
""
""
"Homepage: https://aomedia.googlesource.com/aom"
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver/build" || return 1

  cmake \
    -G "Unix Makefiles" \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR="/lib${LIBDIRSUFFIX}" \
    -DCMAKE_INSTALL_INCLUDEDIR=/include \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_NASM=ON \
    -DENABLE_DOCS=OFF \
    -DBUILD_SHARED_LIBS=ON \
    ../ || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
