#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libaom
pkgver=1.0.0.r1804.gcb43f766c
pkgrel=3slint
url="https://aomedia.googlesource.com/aom"
license=("BSD-2-Clause")
source=("https://aomedia.googlesource.com/aom/+archive/cb43f766c.tar.gz")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"libaom (Open Source Video Codec)"
""
"AOMedia Video 1 (AV1) is designed to be the successor to VP9 and"
"also to eventually be a direct competitor for HEVC/H.265."
""
""
""
""
"Homepage: https://aomedia.googlesource.com/aom"
)

build() {
  local legacyDocName sourceRoot

  legacyDocName="${pkgname}.S""lackBuild"
  sourceRoot="$SRC/$pkgname-$pkgver"

  if [ ! -d "$sourceRoot" ]; then
    sourceRoot="$SRC"
  fi

  mkdir -p "$sourceRoot/build" || return 1
  cd "$sourceRoot/build" || return 1

  cmake \
    -G "Unix Makefiles" \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR="/lib${LIBDIRSUFFIX}" \
    -DCMAKE_INSTALL_INCLUDEDIR=/include \
    -DCMAKE_BUILD_TYPE=Release \
    -DENABLE_NASM=ON \
    -DENABLE_DOCS=OFF \
    -DBUILD_SHARED_LIBS=ON \
    ../ || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  install -Dm0644 "$sourceRoot/AUTHORS" \
    "$PKG/usr/doc/$pkgname-$pkgver/AUTHORS" || return 1
  install -Dm0644 "$sourceRoot/CHANGELOG" \
    "$PKG/usr/doc/$pkgname-$pkgver/CHANGELOG" || return 1
  install -Dm0644 "$sourceRoot/LICENSE" \
    "$PKG/usr/doc/$pkgname-$pkgver/LICENSE" || return 1
  install -Dm0644 "$sourceRoot/PATENTS" \
    "$PKG/usr/doc/$pkgname-$pkgver/PATENTS" || return 1
  install -Dm0644 "$sourceRoot/README.md" \
    "$PKG/usr/doc/$pkgname-$pkgver/README.md" || return 1
  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
