#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-html-parser
pkgver=3.76
pkgrel=1slint
export srcname=HTML-Parser
source=("https://cpan.metacpan.org/authors/id/O/OA/OALDERS/$srcname-$pkgver.tar.gz")
docs=("TODO" "Changes" "README")
url="https://metacpan.org/pod/HTML::Parser"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-html-parser (perl HTML parser module collection)"
"It provides Perl modules that parse and extract"
"information from HTML documents."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  printf 'y\n' | perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  make test || exit 1
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
