#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=fontforge
pkgver=20201107
pkgrel=2slint
slackdesc=\
(
"fontforge: fontforge (an outline font editor)"
"FontForge is an outline font editor that lets you create your own"
"postscript, truetype, opentype, cid-keyed, multi-master, cff, svg"
"and bitmap (bdf, FON, NFNT) fonts, or edit existing ones. It also"
"lets you convert one format to another. FontForge has support for"
"many Macintosh font formats."
)
#Homepage: http://fontforge.sourceforge.net/

url='https://fontforge.github.io/'
makedepends=('cmake' 'git' 'python-sphinx' 'python3')
depends=('libtool' 'pango' 'giflib' 'libtiff' 'libxml2' 'python3'
         'potrace' 'woff2' 'gtk+3' 'libuninameslist')
source=("https://github.com/${pkgname}/${pkgname}/releases/download/${pkgver}/${pkgname}-${pkgver}.tar.xz"
        "fontforge-msgfmt-no-check.patch")
docs=(AUTHORS COPYING.gplv3 LICENSE)
build() {
  cd "$SRC/${pkgname}-${pkgver}" || return 1
  patch -Np1 -i "$SRC/fontforge-msgfmt-no-check.patch" || return 1
  mkdir build || return 1
  cd build || return 1

  # python3.11 in Slint ships without the unversioned libpython symlink.
  # Pass explicit embed artifacts so FindPython3 resolves Development.Embed.
  cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_MAINTAINER_TOOLS=TRUE \
    -DENABLE_FONTFORGE_EXTRAS=TRUE \
    -DENABLE_LIBSPIRO=FALSE \
    -DENABLE_DOCS=FALSE \
    -DENABLE_LIBREADLINE=FALSE \
    -DENABLE_LIBUNINAMESLIST=FALSE \
    -DPython3_EXECUTABLE=/usr/bin/python3.11 \
    -DPython3_INCLUDE_DIR=/usr/include/python3.11 \
    -DPython3_LIBRARY=/usr/lib64/libpython3.11.so.1.0 \
    -DUNIX=TRUE \
    .. || return 1

  sed 's/-R/-Wl,-rpath=/g' CMakeCache.txt > bof || return 1
  mv bof CMakeCache.txt || return 1

  make || return 1
  make DESTDIR="$PKG" install || return 1
}
