.\" matchbox-panel.1
.\" Copyright 2004  Moray Allan
.TH matchbox-panel 1 "Jul 17 2004" ""
.SH NAME
matchbox-panel \- a desktop panel for resource-limited systems
.SH SYNOPSIS
.B matchbox-panel
[\fIoptions\fR]
.SH DESCRIPTION
.B matchbox-panel
is a desktop panel, which can hold small `applets'
such as a clock, system monitor and wireless monitor.

Matchbox is a base environment for the X Window System running on non-desktop
embedded platforms such as handhelds, set-top boxes, kiosks and anything else
for which screen space, input mechanisms or system resources are limited.
.SH OPTIONS
.TP
.BI \-display\  display
X display to connect to
.TP
.BI \-geometry\  geometry
Use \fB\-\-size\fR/\fB\-\-orientation\fR instead
.TP
.BI \-\-id\  int
Panel number
.TP
.BI \-\-size\  int ,\ \-s\  int
Width/height of panel in pixels
.TP
.BI \-\-orientation\  north|east|south|west
.TP
.BI \-\-default\-apps\  app\ list ,\ \-da\  app\ list
Comma-separated list of apps to add to a panel when no session starts
.TP
.BI \-\-margin-start\  +int
Initial app offset in pixels (panel start)
.TP
.BI \-\-margin-end\  +int
Initial app offset in pixels (panel end)
.TP
.B \-\-titlebar
Request panel in titlebar
.TP
.B \-\-no\-session, \-ns
Disable automatic session saving
.TP
.B \-\-no\-menu, \-nm
Disable popup menu
.TP
.B \-\-no\-flip, \-nf
Disable automatic panel rotation when display is rotated
.TP
.B \-\-overide\-bubbles, \-o
Set override\-redirect attribute on popup information windows
.TP
\fB\-\-help\fR
help

.SH AUTHOR
.B matchbox-panel
was written by Matthew Allum <mallum@o-hand.com>.

