.\" mb-applet-battery.1
.\" Copyright 2008 Moray Allan
.TH mb-applet-battery 1 "Mar 24 2008" ""
.SH NAME
mb-applet-battery \- a battery status panel applet
.SH SYNOPSIS
.B mb-applet-battery
.SH DESCRIPTION
.B mb-applet-battery
is a panel applet which displays the amount of battery charge remaining.

Matchbox is a base environment for the X Window System running on non-desktop
embedded platforms such as handhelds, set-top boxes, kiosks and anything else
for which screen space, input mechanisms or system resources are limited.
.SH AUTHOR
.B mb-applet-battery
was written by Matthew Allum <mallum@o-hand.com>.
