.\" mb-applet-launcher.1
.\" Copyright 2004  Moray Allan
.TH mb-applet-launcher 1 "Jul 17 2004" ""
.SH NAME
mb-applet-launcher \- an application launcher panel applet
.SH SYNOPSIS
.B mb-applet-launcher
[\fIoptions\fR] [\fIaction\fR] \fIimage_file\fR \fIapplication\fR
.SH DESCRIPTION
.B mb-applet-launcher
is a panel applet which can be used to start a given application. The
applet displays the PNG or XPM file given on the command line as an icon,
and when the user clicks on the icon the application is started.

Matchbox is a base environment for the X Window System running on non-desktop
embedded platforms such as handhelds, set-top boxes, kiosks and anything else
for which screen space, input mechanisms or system resources are limited.
.\"
.SH OPTIONS
.TP
.BI \-display\  display
X display to connect to
.TP
.BI \-\-title\  title
.TP
.BI \-\-no\-animation
Disable any animations
.TP
.B \-\-start, \-s
Start application immediately
.TP
The default action is to iconize/uniconize the selected application. Other actions can be specified as command-line options:
.TP
.B \-\-kill, \-k
Destroy the application
.TP
.B \-\-respawn, \-l
Respawn multiple instances of the application
.TP
.B \-\-message, \-m
Display output from the application as a message from the panel
.TP
Alternatively, a valid \.desktop file can be given:
.TP
.BI \-\-desktop\  \.desktop_file
Any actions given with this option will have no effect. Similar behaviour can be achieved by including a `SingleInstance=True' key pair in the \.desktop file.
.\"
.SH AUTHOR
.B mb-applet-launcher
was written by Matthew Allum <mallum@o-hand.com>.

