#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python-mistune
_srcname=mistune
pkgver=2.0.5
pkgrel=2slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Python Markdown parser)"
""
"Mistune is a fast Markdown parser written in pure Python."
""
"Homepage: https://github.com/lepture/mistune"
)
url="https://github.com/lepture/mistune"
depends=("python")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/m/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  install -m 0644 LICENSE "$docdir/LICENSE" || return 1
  install -m 0644 README.rst "$docdir/README.rst" || return 1
}
