#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libwpe
pkgver=1.12.0
pkgrel=1slint
source=("https://wpewebkit.org/releases/${pkgname}-${pkgver}.tar.xz")
url="https://wpewebkit.org"
docs=("COPYING" "NEWS")
options=("nosrcpack")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"libwpe (general-purpose library for WPE WebKit)"
""
"WPE is the reference WebKit port for embedded and"
"low-consumption computer devices. It is designed with"
"performance, small footprint, accelerated rendering, and"
"simplicity of deployment in mind, bringing the WebKit"
"engine to many platforms and target devices."
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  cmake -S . -B build \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release || return 1

  cmake --build build -j "$numjobs" || cmake --build build || return 1
  DESTDIR="$PKG" cmake --install build || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
