#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=perl-cairo
pkgver=1.109
pkgrel=1slint
depends=(
  "aaa_libraries|bzip2"
  "aaa_libraries|glib2"
  "aaa_libraries|libpng"
  "aaa_libraries|pcre"
  "aaa_libraries|xz"
  "brotli"
  "cairo"
  "fontconfig"
  "freetype"
  "graphite2"
  "harfbuzz"
  "libX11"
  "libXau"
  "libXdmcp"
  "libXext"
  "libXrender"
  "libglvnd"
  "libxcb"
  "libxml2"
  "pixman"
  "zlib"
)
export srcname=Cairo
source=("https://cpan.metacpan.org/authors/id/X/XA/XAOC/$srcname-$pkgver.tar.gz")
docs=("ChangeLog*" "LICENSE" "NEWS" "README" "TODO")
url="https://metacpan.org/release/Cairo"

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"perl-cairo (Perl bindings for the Cairo graphics library)"
"Provides Perl interfaces to Cairo drawing primitives and surfaces."
)

build() {
  cd "$SRC/$srcname-$pkgver" || exit 1

  perl Makefile.PL \
    OPTIMIZE="$CFLAGS" \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN3DIR=/usr/man/man3
  make || exit 1
  # Keep existing package behavior: skip upstream tests.
  make install DESTDIR="$PKG" || exit 1

  slkbuild_path="${SRC%/src}/SLKBUILD"
  legacy_suffix=SlackBuild
  install -Dm644 "$slkbuild_path" \
    "$PKG/usr/doc/$pkgname-$pkgver/$pkgname.$legacy_suffix" || exit 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete
  find "$PKG" -depth -type d -empty -delete || exit 1
}
