#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libbs2b
pkgver=3.1.0
pkgrel=2slint
url="https://sourceforge.net/projects/bs2b/"
source=("https://downloads.sourceforge.net/project/bs2b/libbs2b/${pkgver}/${pkgname}-${pkgver}.tar.bz2")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"libbs2b (headphone crossfeed library)"
""
"libbs2b provides the Bauer stereophonic-to-binaural DSP"
"library for improving headphone listening of stereo audio."
"It helps reduce listening fatigue without major distortion."
""
"Homepage: https://sourceforge.net/projects/bs2b/"
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  LIBS="-ldl" \
  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/man \
    --docdir="/usr/doc/$pkgname-$pkgver" \
    --build="$ARCH-slackware-linux" || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG"/usr/lib"${LIBDIRSUFFIX}"/*.la || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
