#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libmatroska
pkgver=1.6.3
pkgrel=1slint
url="https://www.matroska.org/downloads/libraries.html"
source=("https://dl.matroska.org/downloads/${pkgname}/${pkgname}-${pkgver}.tar.xz")
docs=("ChangeLog" "LICENSE.LGPL")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"libmatroska (C++ library to parse Matroska files)"
""
"libmatroska is a C++ library to parse Matroska files"
"such as .mkv and .mka."
""
"Homepage: https://www.matroska.org/downloads/libraries.html"
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  cmake -B build -S . \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DLIB_SUFFIX="${LIBDIRSUFFIX}" \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_BUILD_TYPE=Release || return 1
  cmake --build build || return 1
  DESTDIR="$PKG" cmake --install build || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
