notify-osd is Canonical's on-screen-display notification agent,
implementing the freedesktop.org Desktop Notifications Specification
with semi-transparent click-through bubbles.

This package allows Orca to speak the desktop notifications displayed
in a transient window to inform the user of an even that happened or
convey some information.

The directory /usr/share/notify-osd/examples includes source code in C
and Python as binaries of examples
