#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier <didier~at~slint~dot~fr>

pkgname=python3-automat
export srcname=automat
pkgver=25.4.16
pkgrel=1slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (self-service finite-state machines)"
""
"Automat is a library for concise, idiomatic Python expression"
"of finite-state automata, particularly deterministic"
"finite-state transducers."
""
"Homepage: https://github.com/glyph/automat"
)
url="https://github.com/glyph/automat"
depends=("python3")
makedepends=("python3-build" "python3-installer" "python3-setuptools" "python3-wheel")
source=("https://files.pythonhosted.org/packages/e3/0f/d40bbe294bbf004d436a8bcbcfaadca8b5140d39ad0ad3d73d1a8ba15f14/automat-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${srcname}-${pkgver}" || return 1

  python3 -m build --wheel --no-isolation || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  shopt -s nullglob
  for doc in LICENSE README.* docs; do
    [[ -e $doc ]] || continue
    cp -a "$doc" "$docdir/" || return 1
  done
  shopt -u nullglob

  if [[ -d $docdir/docs ]]; then
    find "$docdir/docs" -type f -exec chmod 0644 {} + || return 1
  fi
}
