plank is a dock that after installation can be enabled typing plank-on and
disabled typing plank-off.
If enabled, it will be displayed when starting Mate.	

The version shipped in Slint, maintained by Josh Ellithorpe, comes from:
https://github.com/zquestz/plank-reloaded

By default in Slint plank is positioned on top of the screen.

It is highly configurable with Ctrl+click right on it or typing:
plank --preferences.
In the preferences GUI we suggest to include at least the applications
docklet clicking on its icons in the docklet tab.

Usage:
- When you start a graphical application, its icon is displayed in the Dock.
- Right-click on the icon to pin or unpin it from the dock.
- Right-click on the icon also allows to close it if already running.
- If an icon is pinned, it will be displayed on the Dock even if the
  application is not running.
- Some applications' icons are pinned to the dock by default.
  You can, of course, unpin them.
- If you click on an application icon and it is not already running, it will
  start and get the focus.
- If you click on an application icon already running, it will get the focus.
- By default a small blue dot is displayed on top of the icon for each running
  instance of the corresponding application.
- You can modify the order of the applets and docklets moving them with the
  with the mouse in the dock.   
 
I have no idea about its accessibility.

Didier Spaier
