#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python3-gTTS
export srcname=gTTS
pkgver=2.5.4
pkgrel=2slint
source=("https://github.com/pndurette/gTTS/archive/v${pkgver}/${srcname}-${pkgver}.tar.gz" "saythis")
url="https://github.com/pndurette/gTTS"
license=('MIT')
depends=('python3-click')
makedepends=('python3-build' 'python3-installer' 'python3-wheel')
docs=("LICENSE*" "*.md" "*.rst")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"python3-gTTS (Google Text-to-Speech)"
""
"Python library and CLI tool to interface with Google Translate's"
"text-to-speech API. Write spoken mp3 data to a file, a file-like"
"object (bytestring) for further audio manipulation, or stdout."
)

build() {
  cd "$SRC/${srcname}-${pkgver}" || return 1

  python3 -m build --wheel --no-isolation || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1

  install -Dm755 "$SRC/saythis" "$PKG/usr/bin/saythis" || return 1
}
