#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=gnome-dictionary
pkgver=40.0
pkgrel=2slint
url="https://wiki.gnome.org/Apps/Dictionary"
source=(
  "https://download.gnome.org/sources/${pkgname}/40/${pkgname}-${pkgver}.tar.xz"
  "meson-1.7-merge-file.patch"
)
docs=("COPYING" "README*")
options=("nosrcpack")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"gnome-dictionary (dictionary client for GNOME desktops)"
""
"GNOME Dictionary looks up definitions from dictionary sources"
"using the DICT protocol. It can browse definitions, match"
"similar words, and switch between local or remote sources."
""
"Homepage: https://wiki.gnome.org/Apps/Dictionary"
)

build() {
  cd "$SRC/$pkgname-$pkgver" || return 1

  patch -Np1 -i "$SRC/meson-1.7-merge-file.patch" || return 1

  if [ -f README.md ]; then
    if command -v pandoc >/dev/null 2>&1; then
      pandoc -f gfm -t html5 -o README.html README.md || return 1
    else
      {
        printf '%s\n' '<!DOCTYPE html>' '<html><body><pre>'
        sed \
          -e 's/&/\&amp;/g' \
          -e 's/</\&lt;/g' \
          -e 's/>/\&gt;/g' \
          README.md
        printf '%s\n' '</pre></body></html>'
      } > README.html || return 1
    fi
  fi

  meson setup build \
    --buildtype=release \
    --infodir=/usr/info \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --localstatedir=/var \
    --mandir=/usr/man \
    --prefix=/usr \
    --sysconfdir=/etc || return 1

  "${NINJA:=ninja}" -C build -j "$numjobs" || return 1
  DESTDIR="$PKG" "${NINJA:=ninja}" -C build install || return 1

  rm -f "$PKG"/usr/lib"${LIBDIRSUFFIX}"/*.la || return 1
}
