#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: fourtysixandtwo <fourtysixandtwo@sliderr.net>
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python3-wheel
_srcname=wheel
pkgver=0.41.2
pkgrel=2slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Python wheel package format)"
""
"Wheel is the built-package format for Python."
""
"Homepage: https://github.com/pypa/wheel"
)
url="https://github.com/pypa/wheel"
license=("MIT")
depends=("python3")
makedepends=("python3-installer" "python3-flit_core3.11")
source=("https://files.pythonhosted.org/packages/source/w/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1
  python3 -m flit_core.wheel || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1

  install -Dm 0644 LICENSE.txt "$PKG/usr/doc/$pkgname-$pkgver/LICENSE.txt" || return 1
  install -Dm 0644 README.rst "$PKG/usr/doc/$pkgname-$pkgver/README.rst" || return 1
}
