#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Packager: Didier Spaier didieratslintdotfr

pkgname=python3-requests
srcname=requests
export srcname
pkgver=2.32.5
pkgrel=1slint
source=("https://files.pythonhosted.org/packages/source/r/requests/requests-$pkgver.tar.gz")
url="http://docs.python-requests.org/en/master/"
docs=("*.rst" "LICENSE*" "NOTICE" "PKG-INFO")
depends=("python3")
makedepends=("python3-setuptools")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"python3-requests: python3-requests (HTTP request library for Python 3)"
"python3-requests:"
"python3-requests: Requests lets you send HTTP/1.1 requests."
"python3-requests: No need to manually add query strings to URLs."
"python3-requests: Or form-encode POST data."
"python3-requests: Keep-alive and connection pooling are automatic."
"python3-requests:"
"python3-requests:"
"python3-requests: Homepage: http://docs.python-requests.org/en/master/"
"python3-requests:"
)

build() {
  cd "$SRC/$srcname-$pkgver" || return 1
  python3 setup.py install --root="$PKG" || return 1
}
