#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Packager: sektor

pkgname=pango
pkgver=1.50.14
pkgrel=1
url="https://www.pango.org/"
source=("https://download.gnome.org/sources/${pkgname}/${pkgver%.*}/${pkgname}-${pkgver}.tar.xz")
options=("nosrcpack")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"pango: pango (library for layout and rendering of text)"
"pango:"
"pango: Pango is a library for layout and rendering of text, with an"
"pango: emphasis on internationalization. It can be used anywhere"
"pango: text layout is needed, and forms the core of text and font"
"pango: handling for GTK."
"pango:"
"pango:"
"pango:"
)

build() {
  local docdir

  docdir="$PKG/usr/doc/${pkgname}-${pkgver}"

  cd "$SRC/${pkgname}-${pkgver}" || return 1
  rm -rf meson-build || return 1

  meson setup meson-build . \
    --prefix=/usr \
    --libdir="lib${LIBDIRSUFFIX}" \
    --libexecdir=/usr/libexec \
    --bindir=/usr/bin \
    --sbindir=/usr/sbin \
    --includedir=/usr/include \
    --datadir=/usr/share \
    --mandir=/usr/man \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Dcairo=enabled \
    -Dfreetype=enabled \
    -Dfontconfig=enabled \
    -Dgtk_doc=false \
    -Dinstall-tests=false \
    -Dintrospection=enabled \
    -Dsysprof=disabled \
    -Dxft=enabled || return 1
  "${NINJA:=ninja}" -C meson-build -j "$numjobs" || return 1
  DESTDIR="$PKG" "$NINJA" -C meson-build install || return 1

  rm -f "$PKG"/{,usr/}lib"${LIBDIRSUFFIX}"/*.la || return 1

  install -d "$docdir" || return 1
  cp -a COPYING NEWS README.md README.win32 "$docdir/" || return 1
  find "$docdir" -type f -exec chmod 0644 {} + || return 1
}
