#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Felix Yan <felixonmars@archlinux.org>
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python3-wsaccel
pkgver=0.6.3
pkgrel=3slint
slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Accelerator for ws4py and AutobahnPython)"
)
arch=('x86_64')
url='https://github.com/methane/wsaccel'
license=('Apache')
depends=('python3')
makedepends=('python3-cython' 'python3-setuptools')
checkdepends=('python-pytest-runner')
source=("https://github.com/methane/wsaccel/archive/refs/tags/v0.6.3.tar.gz")
md5sums=('f06b48bcdccc4713ad75234d87679eba')
docs=(LICENSE README.rst ChangeLog)
build() {
  cd "wsaccel-$pkgver" || return 1
  python3 setup.py install --root="$PKG" || return 1
}
