#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=zeitgeist
pkgver=1.0.4
pkgrel=2slint
url="https://launchpad.net/zeitgeist/"
source=(
  "https://launchpad.net/zeitgeist/1.0/${pkgver}/+download/${pkgname}-${pkgver}.tar.xz"
  "zeitgeist-1.0.4-crash-fixes.patch"
)
docs=("AUTHORS" "COPYING*" "README*")
options=("nosrcpack")
depends=(
  "dee"
  "gtk+3"
  "json-glib"
  "sqlite"
  "telepathy-glib"
  "xapian-core"
)
makedepends=(
  "gobject-introspection"
  "python-rdflib"
  "raptor"
  "vala"
)

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"zeitgeist (Service logging user activities and events)"
""
"Zeitgeist is a service that logs user activities and events"
"from applications and exposes that information over D-Bus."
"It also ships a datahub and optional FTS support backed by"
"Xapian."
""
"Homepage: https://launchpad.net/zeitgeist"
)

build() {
  cd "$SRC/$pkgname-$pkgver" || return 1

  patch -Np1 -i "$SRC/zeitgeist-1.0.4-crash-fixes.patch" || return 1

  if [ -f README.md ] && command -v pandoc >/dev/null 2>&1; then
    pandoc -f gfm -t html5 -o README.html README.md || return 1
  fi

  autoreconf -fi || return 1
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --localstatedir=/var \
    --enable-telepathy \
    --enable-introspection \
    --libexecdir=/usr/libexec \
    --enable-fts \
    --with-dee-icu=yes || return 1
  sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool || return 1
  make || return 1
  make DESTDIR="$PKG" install || return 1
}
