This is NOT the perl script from Thomas E. Dickey, cf.
https://invisible-island.net/scripts/man2html.html
This page also provides the history of man2html.

I won't take sides on which is better ;)

Rather, it is the utility shipped in man-1.6g

To avoid any confusion and allow the coexistence of both utilities,
this program is named man2html-1.6g. 

However, the binary file it provides is named man2html

The man-db package imported from Slackware ships the script from Dickey,
that we rename man2html-Dickey.  

it is needed to build the html doc of the package daisy-player.

Didier Spaier
Monday 10 December 2018
