#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python-snowballstemmer
_srcname=snowballstemmer
pkgver=2.2.0
pkgrel=2slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Snowball stemming library for Python)"
""
"snowballstemmer provides Python bindings and modules for"
"the Snowball stemming algorithms used in text analysis."
""
"Homepage: https://github.com/shibukawa/snowball_py"
)
url="https://github.com/shibukawa/snowball_py"
depends=("python")
makedepends=("python-setuptools")
source=("https://files.pythonhosted.org/packages/source/s/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1

  python3 setup.py install --root="$PKG" || return 1

  docdir="$PKG/usr/doc/$pkgname-$pkgver"
  install -d "$docdir" || return 1

  install -m 0644 COPYING "$docdir/COPYING" || return 1
  install -m 0644 NEWS "$docdir/NEWS" || return 1
  install -m 0644 README.rst "$docdir/README.rst" || return 1
}
