#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=libtar
pkgver=1.2.20
pkgrel=3slint
url="https://github.com/tklauser/libtar"
source=(
  "https://downloads.sourceforge.net/project/slackbuildsdirectlinks/libtar/${pkgname}-0907a90.tar.gz"
)
docs=("COPYRIGHT" "ChangeLog-1.0.x" "TODO" "ChangeLog" "INSTALL" "README")
options=("nosrcpack")

slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"libtar (tar file manipulation API)"
""
"libtar is a C library for manipulating POSIX tar"
"files. It handles adding and extracting files to"
"and from tar archives."
""
"Homepage: https://github.com/tklauser/libtar"
)

build() {
  local sourceTree
  local legacyDocName

  sourceTree="${pkgname}-0907a90"
  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$sourceTree" || return 1

  autoreconf -vif || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --mandir=/usr/man \
    --disable-static \
    --build="$ARCH-slackware-linux" || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG"/usr/lib*/*.la || return 1

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
