#!/bin/bash
# shellcheck shell=bash disable=SC2034,SC2154

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=xapp
pkgver=2.8.2
pkgrel=3slint
slackdesc=" $pkgname (Common library for X-Apps project)"
arch=(x86_64)
url="https://github.com/linuxmint/${pkgname}"
license=(GPL)
depends=(libdbusmenu libgnomekbd python3 python3-gobject)
makedepends=(meson ninja gobject-introspection python3-gobject vala)
source=("https://github.com/linuxmint/${pkgname}/archive/${pkgver}/${pkgname}-${pkgver}.tar.gz")
sha256sums=('07b00d02d2bdd93c043e370305071df80f21ded6404f7309b590a8f896e635b2')
b2sums=('1e2fb92b976196c2e9f36e322656ee40252e4c358a13361a054ead88e6fa3df35a53f1b0ee594df4189a68c1739c4a040558fac533ace095536fcc1dca76954b')

build() {
  local sitePackages=""

  cd "$SRC/$pkgname-$pkgver" || return 1

  meson setup build \
    --buildtype=release \
    --infodir=/usr/info \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --localstatedir=/var \
    --mandir=/usr/man \
    --prefix=/usr \
    --sysconfdir=/etc \
    -Ddocs=false \
    -Dstrip=true || return 1

  meson compile -C build -j "$numjobs" || return 1
  DESTDIR="$PKG" meson install -C build || return 1

  sitePackages=$(python3 -c "import site; print(site.getsitepackages()[0])") || return 1
  if [[ -d "$PKG$sitePackages" ]]; then
    python3 -m compileall -o 0 -o 1 -o 2 --hardlink-dupes -s "$PKG" \
      "$PKG$sitePackages" || return 1
  fi

  rm -f "$PKG"/usr/lib"${LIBDIRSUFFIX}"/*.la || return 1
}
