#!/bin/bash
# shellcheck shell=bash disable=SC2034
# Maintainer: Patrick J. Volkerding <volkerdi@slackware.com>
# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=python3-setuptools-scm
_srcname=setuptools_scm
pkgver=9.2.0
pkgrel=2slint
slackdesc=(
#|-----handy-ruler------------------------------------------------------|
"$pkgname (Manage Python versions from SCM)"
""
"setuptools_scm manages Python package versions in SCM metadata."
""
"Homepage: https://github.com/pypa/setuptools_scm"
)
url="https://github.com/pypa/setuptools_scm"
license=("MIT")
depends=("python3-packaging" "python3-setuptools")
makedepends=("python3-build" "python3-installer" "python3-wheel")
source=("https://files.pythonhosted.org/packages/source/s/${_srcname}/${_srcname}-${pkgver}.tar.gz")
options=("nosrcpack")

build() {
  cd "$SRC/${_srcname}-${pkgver}" || return 1
  python3 -m build --wheel --no-isolation || return 1
  python3 -m installer --destdir="$PKG" dist/*.whl || return 1

  install -Dm 0644 LICENSE "$PKG/usr/doc/$pkgname-$pkgver/LICENSE" || return 1
  install -Dm 0644 README.md "$PKG/usr/doc/$pkgname-$pkgver/README.md" || return 1
  if [[ -f PKG-INFO ]]; then
    install -Dm 0644 PKG-INFO "$PKG/usr/doc/$pkgname-$pkgver/PKG-INFO" || return 1
  fi
  if [[ -f CHANGELOG.md ]]; then
    head -n 1000 CHANGELOG.md > "$PKG/usr/doc/$pkgname-$pkgver/CHANGELOG.md" || return 1
    touch -r CHANGELOG.md "$PKG/usr/doc/$pkgname-$pkgver/CHANGELOG.md" || return 1
  fi
  if [[ -d docs ]]; then
    cp -a docs "$PKG/usr/doc/$pkgname-$pkgver/docs" || return 1
    find "$PKG/usr/doc/$pkgname-$pkgver/docs" -type f -exec chmod 0644 {} +
  fi
}
