#!/bin/bash
# shellcheck shell=bash disable=SC2034

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=i3
pkgver=4.22
pkgrel=3slint
url="https://www.i3wm.org/"
source=(
  "https://i3wm.org/downloads/${pkgname}-${pkgver}.tar.xz"
  "c305798d42.patch"
  "do_not_symlink_i3_with_shmlog_in_Slint.diff"
  "README.Slint"
  "xinitrc.i3"
)
options=("noautodotnew" "nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"i3 (an improved dynamic tiling window manager)"
"i3 is a tiling window manager written from scratch with strong"
"multi-monitor support and a minimal, keyboard-driven workflow."
)

doinst() {
  cat <<'EOF'
config() {
  NEW="$1"
  OLD="$(dirname "$NEW")/$(basename "$NEW" .new)"
  if [ ! -r "$OLD" ]; then
    mv "$NEW" "$OLD"
  elif [ "$(cat "$OLD" | md5sum)" = "$(cat "$NEW" | md5sum)" ]; then
    rm "$NEW"
  fi
}

config etc/i3/config.new
config etc/i3/config.keycodes.new

if [ -x /usr/bin/update-desktop-database ]; then
  /usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi
EOF
}

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  patch -p1 --verbose < "$SRC/c305798d42.patch" || return 1
  patch -p1 --verbose < "$SRC/do_not_symlink_i3_with_shmlog_in_Slint.diff" || return 1

  meson setup build \
    -Dmans=true \
    -Ddocs=true \
    --prefix /usr \
    --libdir "/usr/lib${LIBDIRSUFFIX}" \
    --mandir /usr/man \
    --sysconfdir /etc \
    --localstatedir /var || return 1
  ninja -C build || return 1
  DESTDIR="$PKG" ninja -C build install || return 1

  mv "$PKG/etc/i3/config" "$PKG/etc/i3/config.new" || return 1
  mv "$PKG/etc/i3/config.keycodes" "$PKG/etc/i3/config.keycodes.new" || return 1
  sed -i 's/i3-sensible-terminal/xterm/' "$PKG/etc/i3/config.new" || return 1

  install -Dm0755 "$SRC/xinitrc.i3" "$PKG/etc/X11/xinit/xinitrc.i3" || return 1

  install -d "$PKG/usr/doc/$pkgname-$pkgver/html" "$PKG/usr/doc/$pkgname-$pkgver/txt" || return 1
  cp -a "$SRC/README.Slint" "$PKG/usr/doc/$pkgname-$pkgver/" || return 1
  cp -a DEPENDS LICENSE RELEASE-NOTES-* "$PKG/usr/doc/$pkgname-$pkgver" || return 1
  cp -a docs/* "$PKG/usr/doc/$pkgname-$pkgver/txt" || return 1
  (
    cd "$PKG/usr/doc/$pkgname-$pkgver/txt" || return 1
    shopt -s nullglob
    mv -- ./*.html ./*.png ./*.css ../html/ || true
    rm -f -- i3-pod2html ./*.conf ./*.dia
  ) || return 1

  rm -rf "$PKG/usr/share/doc"
  rm -f "$PKG/usr/share/xsessions/i3-with-shmlog.desktop"

  cd AnyEvent-I3 || return 1
  perl Makefile.PL \
    PREFIX=/usr \
    INSTALLDIRS=vendor \
    INSTALLVENDORMAN1DIR=/usr/man/man1 \
    INSTALLVENDORMAN3DIR=/usr/man/man3 || return 1
  make || return 1
  make test || return 1
  make install DESTDIR="$PKG" || return 1

  find "$PKG" \( -name perllocal.pod -o -name .packlist -o -name '*.bs' \) -delete || return 1

  install -d "$PKG/usr/doc/$pkgname-$pkgver/AnyEvent-I3" || return 1
  cp -a Changes README MANIFEST "$PKG/usr/doc/$pkgname-$pkgver/AnyEvent-I3/" || return 1

  if [ -d "$PKG/usr/man" ]; then
    find "$PKG/usr/man" -type f -exec gzip -9 {} + || return 1
    while IFS= read -r -d '' manPage; do
      ln -s "$(readlink "$manPage").gz" "${manPage}.gz" || return 1
      rm -f "$manPage" || return 1
    done < <(find "$PKG/usr/man" -type l -print0)
  fi

  find "$PKG" -depth -type d -empty -delete || true

  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
