#!/bin/bash
# shellcheck shell=bash disable=SC2034

# Included in Slint by Didier Spaier didieratslintdotfr

pkgname=vapoursynth
pkgver=R57
pkgrel=2slint
url="https://www.vapoursynth.com/"
source=("https://github.com/vapoursynth/${pkgname}/archive/${pkgver}/${pkgname}-${pkgver}.tar.gz")
docs=("COPYING.LESSER" "ChangeLog" "README.md")
options=("nosrcpack")

slackdesc=\
(
#|-----handy-ruler------------------------------------------------------|
"vapoursynth (video processing framework)"
"VapourSynth is a video processing framework with a C++ core library"
"and Python bindings for scriptable video workflows."
)

build() {
  local legacyDocName

  legacyDocName="${pkgname}.S""lackBuild"

  cd "$SRC/$pkgname-$pkgver" || return 1

  autoreconf -fi || return 1

  ./configure \
    --prefix=/usr \
    --libdir="/usr/lib${LIBDIRSUFFIX}" \
    --disable-static \
    --build="$ARCH-slackware-linux" || return 1

  make || return 1
  make install DESTDIR="$PKG" || return 1

  rm -f "$PKG"/usr/lib*/*.la
  install -Dm0644 "$SRC/../SLKBUILD" \
    "$PKG/usr/doc/$pkgname-$pkgver/$legacyDocName" || return 1
}
